export const STATUS = {
  SOLICITADO:   'solicitado',
  AG_COTACAO:   'ag_cotacao',
  EM_APROVACAO: 'em_aprovacao',
  APROVADO:     'aprovado',
  COMPRADO:     'comprado',
  ENTREGUE:     'entregue',
  PAGO:         'pago',
  REPROVADO:    'reprovado',
  CANCELADO:    'cancelado',
}

export const STATUS_LABEL = {
  solicitado:   'Solicitado',
  ag_cotacao:   'Ag. cotação',
  em_aprovacao: 'Em aprovação',
  aprovado:     'Aprovado',
  comprado:     'Comprado',
  entregue:     'Entregue',
  pago:         'Pago',
  reprovado:    'Reprovado',
  cancelado:    'Cancelado',
}

export const STATUS_COLOR = {
  solicitado:   'neutral',
  ag_cotacao:   'blue',
  em_aprovacao: 'gold',
  aprovado:     'green',
  comprado:     'green',
  entregue:     'green',
  pago:         'green',
  reprovado:    'red',
  cancelado:    'red',
}

export const STATUS_DOT_COLOR = {
  solicitado:   'dot-gray',
  ag_cotacao:   'dot-blue',
  em_aprovacao: 'dot-gold',
  aprovado:     'dot-green',
  comprado:     'dot-green',
  entregue:     'dot-green',
  pago:         'dot-green',
  reprovado:    'dot-red',
  cancelado:    'dot-red',
}

export const PERFIS = {
  SUPREMO:     'supremo',
  GESTOR:      'gestor',
  APROVADOR:   'aprovador',
  COMPRADOR:   'comprador',
  FINANCEIRO:  'financeiro',
  SOLICITANTE: 'solicitante',
}

export const PERFIS_LABEL = {
  supremo:     'Supremo',
  gestor:      'Gestor',
  aprovador:   'Aprovador',
  comprador:   'Comprador',
  financeiro:  'Financeiro',
  solicitante: 'Solicitante',
}

export const PERFIS_COLOR = {
  supremo:     'gold',
  gestor:      'green',
  aprovador:   'blue',
  comprador:   'neutral',
  financeiro:  'neutral',
  solicitante: 'neutral',
}

export const MOTIVOS_REPROVACAO = [
  'Valor acima do orçamento',
  'Cotações insuficientes',
  'Justificativa inadequada',
  'Fornecedor não aprovado',
  'Outros',
]

export const MOTIVOS_CANCELAMENTO = [
  'Compra não necessária',
  'Fornecedor indisponível',
  'Erro no pedido',
  'Pedido duplicado',
  'Outros',
]

export const CATEGORIAS_PADRAO = [
  { nome: 'Manutenção',       cor: '#E05040' },
  { nome: 'Escritório',       cor: '#5BA3E0' },
  { nome: 'Operacional',      cor: '#C8A96E' },
  { nome: 'Alimentação',      cor: '#4EC08A' },
  { nome: 'Uniformes e EPIs', cor: '#A07FD0' },
  { nome: 'Marketing',        cor: '#E0A040' },
  { nome: 'TI',               cor: '#40B8D0' },
  { nome: 'Serviços',         cor: '#8A8278' },
]

export const EVENTOS = {
  PEDIDO_URGENTE:        'pedido_urgente',
  AG_COTACAO:            'ag_cotacao',
  COMPRADOR_ASSUMIU:     'comprador_assumiu',
  COTACOES_PRONTAS:      'cotacoes_prontas',
  PEDIDO_APROVADO:       'pedido_aprovado',
  PEDIDO_REPROVADO:      'pedido_reprovado',
  PEDIDO_CANCELADO:      'pedido_cancelado',
  PEDIDO_COMPRADO:       'pedido_comprado',
  PEDIDO_ENTREGUE:       'pedido_entregue',
  PARCELA_VENCENDO:      'parcela_vencendo',
  PARCELA_VENCIDA:       'parcela_vencida',
  MENCAO_COMENTARIO:     'mencao_comentario',
  PEDIDO_PARADO:         'pedido_parado',
  PEDIDO_ENTREGUE_SOLIC: 'pedido_entregue_solic',
}

export const EVENTOS_ICON_CLASS = {
  pedido_urgente:        'notif-icon-red',
  ag_cotacao:            'notif-icon-blue',
  comprador_assumiu:     'notif-icon-gold',
  cotacoes_prontas:      'notif-icon-blue',
  pedido_aprovado:       'notif-icon-green',
  pedido_reprovado:      'notif-icon-red',
  pedido_cancelado:      'notif-icon-red',
  pedido_comprado:       'notif-icon-green',
  pedido_entregue:       'notif-icon-green',
  parcela_vencendo:      'notif-icon-gold',
  parcela_vencida:       'notif-icon-red',
  mencao_comentario:     'notif-icon-gold',
  pedido_parado:         'notif-icon-gold',
  pedido_entregue_solic: 'notif-icon-green',
}

export const UNIDADES = [
  'un', 'cx', 'kg', 'L', 'm', 'm²', 'm³',
  'par', 'pct', 'kit', 'rolo', 'saco',
  'hora', 'mês', 'pessoa', 'licença', 'serviço',
]

export const CONDICAO_PAGAMENTO = {
  antecipado:         'Antecipado',
  apos_recebimento:   'Após recebimento',
}

// ── Traduções ────────────────────────────────────────────────
export const TRADUCOES = {
  pt: {
    // Login / auth
    titulo:           'Pedidos',
    relatorios:       'Relatórios',
    configuracoes:    'Configurações',
    btnEntrar:        'Entrar',
    btnDemo:          'Acessar modo demo',
    tagline:          'Gestão de compras corporativas',
    emailLabel:       'E-mail',
    senhaLabel:       'Senha',
    esqueci:          'Esqueci a senha',
    escolherIdioma:   'Escolha o idioma do demo',
    continuar:        'Continuar',
    voltar:           'Voltar',
    novoPedido:       'Novo pedido',
    todos:            'Todos',
    urgentes:         'Urgentes',
    meusPedidos:      'Meus pedidos',
    estaSemana:       'Esta semana',
    encerrados:       'Encerrados',
    resetEnviado:     'E-mail de recuperação enviado',
    resetMsg:         'Verifique sua caixa de entrada e siga as instruções para redefinir sua senha.',
    emailReset:       'Digite seu e-mail para receber o link de recuperação',
    enviarLink:       'Enviar link',

    // Shared UI
    fechar:           'Fechar',
    cancelar:         'Cancelar',
    salvar:           'Salvar',
    confirmar:        'Confirmar',
    editar:           'Editar',
    excluir:          'Excluir',
    selecionar:       'Selecionar…',
    opcional:         'Opcional',
    limpar:           'Limpar',

    // Topbar tooltips
    tooltipTema:      'Alternar tema',
    tooltipNotif:     'Notificações',
    tooltipConfig:    'Configurações',
    tooltipCmd:       'Paleta de comandos (Ctrl+K)',

    // Pedidos toolbar / pills
    meusPendentes:    'Meus pendentes',
    buscarPedido:     'Buscar pedido…',
    salvarVisao:      'Salvar visão',
    periodo:          'Período:',

    // List filters & columns
    todasEmpresas:    'Todas as empresas',
    todasCategorias:  'Todas as categorias',
    TodosCompradores: 'Todos os compradores',
    limparFiltros:    'Limpar filtros',
    colPedido:        'Pedido',
    colEmpresa:       'Empresa',
    colSolicitante:   'Solicitante',
    colValorEst:      'Valor est.',
    colData:          'Data',
    paginaAnt:        'Anterior',
    paginaProx:       'Próxima',

    // Kanban empty states
    semPedidosColuna: 'Sem pedidos aqui',
    nenhumResultado:  'Nenhum resultado encontrado',
    nenhumPedido:     'Nenhum pedido por aqui ainda',
    ajustarFiltro:    'Tente ajustar o filtro ou o termo de busca.',
    abrirPrimeiro:    'Abra o primeiro pedido clicando em "Novo pedido".',

    // New order modal
    npTitulo:           'Título',
    npTituloPlaceholder:'Ex: Caixa de luvas descartáveis',
    npEmpresa:          'Empresa',
    npQuantidade:       'Quantidade',
    npUnidade:          'Unidade',
    npData:             'Necessário até',
    npValor:            'Valor estimado',
    npCC:               'Centro de custo',
    npCategoria:        'Categoria',
    npUrgente:          'Pedido urgente',
    npObs:              'Observações',
    npObsPlaceholder:   'Descreva detalhes relevantes para a compra…',
    btnAbrirPedido:     'Abrir pedido',
    duplicarPedido:     'Duplicar pedido',

    // Saved views
    nomeVisao:          'Nome da visão',
    nomeVisaoPlaceholder:'Ex: Urgentes da semana',

    // Bulk actions
    exportarCSV:          'Exportar CSV',
    cancelarSelecionados: 'Cancelar selecionados',
    desmarcarTudo:        'Desmarcar tudo',

    // Order detail — action buttons
    btnExportarPDF:       'Exportar PDF',
    btnDuplicar:          'Duplicar',
    btnReabrir:           'Reabrir pedido',
    btnCancelarPedido:    'Cancelar pedido',
    btnAssumirPedido:     'Assumir pedido',
    btnLiberarPedido:     'Liberar pedido',
    btnAprovar:           'Aprovar',
    btnReprovar:          'Reprovar',
    btnExecutarCompra:    'Executar compra',
    btnConfirmarEntrega:  'Confirmar entrega',
    btnConfirmarPagamento:'Confirmar pagamento',
    btnEditarPedido:      'Editar pedido',

    // Order detail — sections & UI
    secaoAnexos:          'Anexos',
    secaoAtividade:       'Atividade',
    secaoCotacoes:        'Cotações',
    secaoParcelas:        'Parcelas',
    btnAdicionarAnexo:    'Adicionar',
    btnComparar:          'Comparar',
    btnNovaCotacao:       'Nova cotação',
    btnAdicionarParcela:  'Adicionar parcela',
    btnEnviarComentario:  'Enviar',
    placeholderComentario:'Comentar… use @ para mencionar',

    // Order detail — meta labels & people
    metaEmpresa:          'Empresa',
    metaQtd:              'Quantidade',
    metaCategoria:        'Categoria',
    metaNecessario:       'Necessário até',
    metaValorEst:         'Valor estimado',
    metaCentro:           'Centro de custo',
    metaValorFinal:       'Valor final',
    metaDataCompra:       'Data da compra',
    metaDataEntrega:      'Data de entrega',
    pessoasEnvolvidas:    'Pessoas envolvidas',
    solicitanteLabel:     'Solicitante',
    criouPedido:          'Criou o pedido',
    compradorLabel:       'Comprador',
    semCotacoes:          'Sem cotações',
    aguardandoComprador:  'Aguardando comprador',
    aprovadoresLabel:     'Aprovadores',
    aprovadoStatus:       'Aprovado',
    aguardandoStatus:     'Aguardando',
    urgente:              'Urgente',
    economiaLabel:        'Economia',
    reabertoDe:           'Reaberto a partir de',
    reabertoComo:         'Reaberto como',

    // Order detail — modal labels
    confirmarCompra:           'Confirmar compra',
    fornecedorLabel:           'Fornecedor',
    valorFinalLabel:           'Valor final',
    condicaoPagLabel:          'Condição de pagamento',
    dataCompraLabel:           'Data da compra',
    numParcelasLabel:          'Número de parcelas',
    vencimentoPrimeiraLabel:   'Vencimento da 1ª parcela',
    selecionar:                'Selecionar…',
    especifique:               'Especifique',
    especifiquePlaceholder:    'Descreva o motivo…',
    justReaberturaLabel:       'Justificativa de reabertura',
    justReaberturaPlaceholder: 'Explique o que mudou ou por que está reabrindo este pedido…',
    reabrirDescricao:          'Um novo pedido será criado em Solicitado com os dados deste, vinculado ao original. Este pedido continua como Reprovado.',
    btnCancelar:               'Cancelar',
    tituloReprovar:            'Reprovar pedido',
    tituloCancelar:            'Cancelar pedido',
    tituloReabrir:             'Reabrir pedido',

    // Toast / feedback messages — order detail
    pedidoNaoEncontrado:       'Pedido não encontrado',
    pedidoRemovidoMsg:         'O pedido que você tentou acessar não existe ou foi removido.',
    semAcessoPedido:           'Você não tem permissão para acessar este pedido.',
    erroCarregarPedido:        'Erro ao carregar pedido.',
    pedidoJaAssumido:          'Pedido já foi assumido por outro comprador.',
    pedidoAssumido:            'Pedido assumido!',
    erroAssumir:               'Erro ao assumir pedido.',
    pedidoLiberado:            'Pedido liberado para a fila.',
    erroLiberarPedido:         'Erro ao liberar pedido.',
    pedidoJaProcessado:        'Este pedido já foi processado por outro aprovador.',
    pedidoAprovado:            'Pedido aprovado!',
    erroAprovar:               'Erro ao aprovar.',
    selecionarMotivoSimples:   'Selecione um motivo.',
    pedidoReprovado:           'Pedido reprovado.',
    erroReprovar:              'Erro ao reprovar.',
    compraRegistrada:          'Compra registrada!',
    erroRegistrarCompra:       'Erro ao registrar compra.',
    entregaConfirmada:         'Entrega confirmada!',
    erroConfirmarEntrega:      'Erro ao confirmar entrega.',
    pagamentoConfirmado:       'Pagamento confirmado!',
    erroConfirmarPagamento:    'Erro ao confirmar pagamento.',
    pedidoCanceladoMsg:        'Pedido cancelado.',
    erroCancelarPedido:        'Erro ao cancelar pedido.',
    pedidoAtualizado:          'Pedido atualizado!',
    erroSalvarAlteracoes:      'Erro ao salvar alterações.',
    erroEnviarComentario:      'Erro ao enviar comentário.',
    cotacaoIndicada:           'Cotação indicada!',
    erroIndicarCotacao:        'Erro ao indicar cotação.',
    pagamentoRegistrado:       'Pagamento registrado!',
    erroRegistrarPagamento:    'Erro ao registrar pagamento.',
    comprovanteAnexado:        'Comprovante anexado!',
    erroAnexarComprovante:     'Erro ao anexar comprovante.',
    fornecedorValorObrig:      'Fornecedor e valor são obrigatórios.',
    cotacaoAdicionada:         'Cotação adicionada!',
    erroSalvarCotacao:         'Erro ao salvar cotação.',
    pdfExportado:              'PDF exportado.',
    erroExportarPDF:           'Erro ao exportar PDF. Verifique a conexão.',
    informarJustificativa:     'Informe a justificativa de reabertura.',
    pedidoReabertoComo:        'Pedido reaberto como',
    tipoNaoPermitido:          'Tipo não permitido. Use PDF, imagem (JPG/PNG/WebP), DOCX ou XLSX.',
    arquivoMuitoGrande:        'excede o limite de 10 MB.',
    erroEnviarAnexo:           'Erro ao enviar: ',
    anexoRemovido:             'Anexo removido.',
    erroRemoverAnexo:          'Erro ao remover: ',

    // Dashboard
    dashTotalGasto:       'Total gasto no período',
    dashTotalPedidos:     'Total de pedidos',
    dashAgAprovacao:      'Ag. aprovação',
    dashAVencer:          'Parcelas a vencer (7 dias)',
    dashEconomia:         'Economia acumulada',
    dashEconomiaVs:       'Cotações vs. melhor preço',
    dashExportar:         'Exportar',
    dashExportarExcel:    'Exportar Excel',
    dashExportarPDF:      'Exportar PDF',
    dashGastoPorEmpresa:  'Gasto por empresa',
    dashProxParcelas:     'Próximas parcelas',
    dashStatus:           'Status dos pedidos',
    dashGastoPorCategoria:'Gasto por categoria',
    dashGastoMensal:      'Gasto mensal — últimos 6 meses',
    dashEvolucaoGastos:   'Evolução de gastos',
    dashPeriodo:          'Período',
    dashVisao:            'Visão financeira e operacional',
    semDados:             'Sem dados no período.',
    semUrgentes:          'Sem urgentes',
    nenhumaParcela:       'Nenhuma parcela a vencer.',
    dashHoje:             'Hoje',
    periodoMes:           'Este mês',
    periodoTri:           'Este trimestre',
    periodoAno:           'Este ano',
    periodoLivre:         'Período selecionado',
    filtroPilulaMes:      'Mês',
    filtroPilulaTri:      'Trimestre',
    filtroPilulaAno:      'Ano',
    filtroPilulaLivre:    'Livre',
    filtroPilulaAte:      'até',
    noPeriodo:            'No período',
    parcela:              'parcela',
    parcelas:             'parcelas',
    parcelaNum:           'Parcela',

    // Config
    configUsuarios:       'Usuários',
    configCadastros:      'Cadastros',
    configGeral:          'Geral',
    btnNovoUsuario:       'Novo usuário',
    btnNovaEmpresa:       'Nova empresa',
    btnNovaCategoria:     'Nova categoria',
    btnNovoFornecedor:    'Novo fornecedor',
    secaoEmpresas:        'Empresas',
    secaoCategorias:      'Categorias',
    secaoFornecedores:    'Fornecedores',
    editarLabel:          'Editar',
    salvarLabel:          'Salvar',
    novoUsuarioTitulo:    'Novo usuário',
    editarUsuarioTitulo:  'Editar usuário',
    novaEmpresaTitulo:    'Nova empresa',
    editarEmpresaTitulo:  'Editar empresa',
    novaCategoriaTitulo:  'Nova categoria',
    editarCategoriaTitulo:'Editar categoria',
    editarFornTitulo:     'Editar fornecedor',
    nomeObrigatorio:      'Nome é obrigatório.',
    emailObrigatorio:     'E-mail é obrigatório.',
    emailInvalido:        'E-mail em formato inválido.',
    perfilObrigatorio:    'Selecione um perfil.',
    empresaObrigatoria:   'Vincule pelo menos uma empresa.',
    modoDemo:             'Não é possível alterar no modo demo.',
    usuarioAtualizado:    'Usuário atualizado!',
    usuarioCriado:        'Usuário criado! Configure a senha no Firebase Authentication.',
    usuarioExcluido:      'Usuário excluído.',
    empresaAtualizada:    'Empresa atualizada!',
    empresaCriada:        'Empresa criada!',
    categoriaAtualizada:  'Categoria atualizada!',
    categoriaCriada:      'Categoria criada!',
    fornecedorAtualizado: 'Fornecedor atualizado!',
    erroSalvar:           'Erro ao salvar.',
    erroExcluir:          'Erro ao excluir.',
    semEmpresas:           'Nenhuma empresa cadastrada.',
    semFornecedores:       'Nenhum fornecedor cadastrado.',
    empresaAtivaLabel:     'Ativa',
    empresaInativaLabel:   'Inativa',
    cnpjNaoInformado:      'CNPJ não informado',
    categoriaPadraoLabel:  'Padrão',
    catPersonalizadaLabel: 'Personalizada',
    usosPedido:            'pedido',
    usosPedidos:           'pedidos',
    configGeral:           'Geral',
    demoTitulo:            'Dados de demonstração',
    demoDesc:              'Redefine todos os pedidos, cotações e histórico do ambiente demo para os dados de exemplo padrão. Esta ação apaga os dados atuais e não pode ser desfeita.',
    btnResetarDemo:        'Resetar dados demo',
    demoAguarde:           'Aguarde…',
    demoResetadoMsg:       'Dados demo resetados com sucesso!',
    demoErroReset:         'Erro ao resetar dados demo.',
    confirmarResetDemo:    'Isso vai apagar todos os pedidos e recriar os dados de exemplo. Continuar?',
    tourTitulo:            'Tour de apresentação',
    tourDesc:              'Reveja o tour de boas-vindas que apresenta os principais recursos do sistema.',
    btnVerTour:            'Ver tour',
    erroMarcarLidas:       'Não foi possível marcar as notificações como lidas.',
    erroMarcarLida:        'Não foi possível marcar a notificação como lida.',
    novaNotificacao:       'Nova notificação',
    erroAcessarDemo:       'Erro ao acessar modo demo. Tente novamente.',
    erroEnviarEmail:       'Erro ao enviar e-mail. Verifique o endereço.',
    erroSair:              'Erro ao sair. Tente novamente.',
    recuperarSenha:        'Recuperar senha',
    entrando:              'Entrando…',

    // Offline / errors
    semConexao:           'Sem conexão · as alterações serão enviadas quando a conexão for restabelecida.',
    conexaoRestabelecida: 'Conexão restabelecida.',
    erroCarregar:         'Erro ao carregar. Verifique sua conexão.',
    semAcesso:            'Sem acesso',
    semAcessoMsg:         'Você não tem permissão para visualizar este pedido, ou ele não existe.',

    // Tour
    tourStep1Titulo:  'Kanban de pedidos',
    tourStep1Desc:    'Aqui estão todos os pedidos, organizados por etapa do fluxo de compras.',
    tourStep2Titulo:  'Novo pedido',
    tourStep2Desc:    'Crie um pedido de compra em segundos. Preencha o que precisa e envie para aprovação.',
    tourStep3Titulo:  'Notificações',
    tourStep3Desc:    'Fique informado de tudo que muda nos seus pedidos — aprovações, reprovações e menções.',
    tourStep4Titulo:  'Aparência',
    tourStep4Desc:    'Escolha a aparência que prefere: modo escuro ou claro.',
    tourStep5Titulo:  'Configurações',
    tourStep5Desc:    'Gerencie usuários, empresas e categorias do sistema.',
    tourPular:        'Pular tour',
    tourProximo:      'Próximo',
    tourConcluir:     'Concluir',

    // Topbar / nav
    navPedidos:             'Pedidos',
    navRelatorios:          'Relatórios',
    navConfiguracoes:       'Configurações',
    navSair:                'Sair',
    tooltipPaleta:          'Paleta de comandos (Ctrl+K)',
    tooltipNotificacoes:    'Notificações',
    tooltipFecharConfig:    'Fechar configurações',
    tooltipSair:            'Sair da conta',
    tooltipMenu:            'Menu',
    confirmarSair:          'Sair do sistema?',

    // Pluralizáveis
    selecionado:      'selecionado',
    selecionados:     'selecionados',
    pedidoExportado:  'pedido exportado',
    pedidosExportados:'pedidos exportados',
    pedidoCancelado:  'pedido cancelado',
    pedidosCancelados:'pedidos cancelados',

    // Erros / feedback
    confirmarCancelamento: 'Confirmar cancelamento',
    motivoLabel:           'Motivo',
    motivoPlaceholder:     'Selecionar motivo…',
    motivoOutros:          'Descreva o motivo',
    erroCarregarPedidos:   'Não foi possível carregar os pedidos',
    verificarConexao:      'Verifique sua conexão e recarregue a página.',
    erroCamposObrigatorios:'Preencha todos os campos obrigatórios.',
    bulkNenhumCancelavel:  'Nenhum pedido selecionado pode ser cancelado com seu perfil.',
    selecionarMotivo:      'Selecione o motivo de cancelamento.',
    descreverMotivo:       'Descreva o motivo.',
    erroCancelarPedidos:   'Erro ao cancelar pedidos: ',
    seraoCancelados:       'serão cancelados',
  },

  en: {
    // Login / auth
    titulo:           'Orders',
    relatorios:       'Reports',
    configuracoes:    'Settings',
    btnEntrar:        'Sign in',
    btnDemo:          'Try demo mode',
    tagline:          'Corporate procurement management',
    emailLabel:       'Email',
    senhaLabel:       'Password',
    esqueci:          'Forgot password',
    escolherIdioma:   'Choose demo language',
    continuar:        'Continue',
    voltar:           'Back',
    novoPedido:       'New order',
    todos:            'All',
    urgentes:         'Urgent',
    meusPedidos:      'My orders',
    estaSemana:       'This week',
    encerrados:       'Closed',
    resetEnviado:     'Recovery email sent',
    resetMsg:         'Check your inbox and follow the instructions to reset your password.',
    emailReset:       'Enter your email to receive the recovery link',
    enviarLink:       'Send link',

    // Shared UI
    fechar:           'Close',
    cancelar:         'Cancel',
    salvar:           'Save',
    confirmar:        'Confirm',
    editar:           'Edit',
    excluir:          'Delete',
    selecionar:       'Select…',
    opcional:         'Optional',
    limpar:           'Clear',

    // Topbar tooltips
    tooltipTema:      'Toggle theme',
    tooltipNotif:     'Notifications',
    tooltipConfig:    'Settings',
    tooltipCmd:       'Command palette (Ctrl+K)',

    // Pedidos toolbar / pills
    meusPendentes:    'My pending',
    buscarPedido:     'Search order…',
    salvarVisao:      'Save view',
    periodo:          'Period:',

    // List filters & columns
    todasEmpresas:    'All companies',
    todasCategorias:  'All categories',
    TodosCompradores: 'All buyers',
    limparFiltros:    'Clear filters',
    colPedido:        'Order',
    colEmpresa:       'Company',
    colSolicitante:   'Requester',
    colValorEst:      'Est. value',
    colData:          'Date',
    paginaAnt:        'Previous',
    paginaProx:       'Next',

    // Kanban empty states
    semPedidosColuna: 'No orders here',
    nenhumResultado:  'No results found',
    nenhumPedido:     'No orders here yet',
    ajustarFiltro:    'Try adjusting the filter or search term.',
    abrirPrimeiro:    'Create your first order by clicking "New order".',

    // New order modal
    npTitulo:           'Title',
    npTituloPlaceholder:'E.g. Box of disposable gloves',
    npEmpresa:          'Company',
    npQuantidade:       'Quantity',
    npUnidade:          'Unit',
    npData:             'Needed by',
    npValor:            'Estimated value',
    npCC:               'Cost center',
    npCategoria:        'Category',
    npUrgente:          'Urgent order',
    npObs:              'Notes',
    npObsPlaceholder:   'Describe relevant details for the purchase…',
    btnAbrirPedido:     'Open order',
    duplicarPedido:     'Duplicate order',

    // Saved views
    nomeVisao:          'View name',
    nomeVisaoPlaceholder:'E.g. Urgent this week',

    // Bulk actions
    exportarCSV:          'Export CSV',
    cancelarSelecionados: 'Cancel selected',
    desmarcarTudo:        'Deselect all',

    // Order detail — action buttons
    btnExportarPDF:       'Export PDF',
    btnDuplicar:          'Duplicate',
    btnReabrir:           'Reopen order',
    btnCancelarPedido:    'Cancel order',
    btnAssumirPedido:     'Claim order',
    btnLiberarPedido:     'Release order',
    btnAprovar:           'Approve',
    btnReprovar:          'Reject',
    btnExecutarCompra:    'Execute purchase',
    btnConfirmarEntrega:  'Confirm delivery',
    btnConfirmarPagamento:'Confirm payment',
    btnEditarPedido:      'Edit order',

    // Order detail — sections & UI
    secaoAnexos:          'Attachments',
    secaoAtividade:       'Activity',
    secaoCotacoes:        'Quotes',
    secaoParcelas:        'Installments',
    btnAdicionarAnexo:    'Add',
    btnComparar:          'Compare',
    btnNovaCotacao:       'New quote',
    btnAdicionarParcela:  'Add installment',
    btnEnviarComentario:  'Send',
    placeholderComentario:'Comment… use @ to mention',

    // Order detail — meta labels & people
    metaEmpresa:          'Company',
    metaQtd:              'Quantity',
    metaCategoria:        'Category',
    metaNecessario:       'Needed by',
    metaValorEst:         'Estimated value',
    metaCentro:           'Cost center',
    metaValorFinal:       'Final value',
    metaDataCompra:       'Purchase date',
    metaDataEntrega:      'Delivery date',
    pessoasEnvolvidas:    'People involved',
    solicitanteLabel:     'Requester',
    criouPedido:          'Created the order',
    compradorLabel:       'Buyer',
    semCotacoes:          'No quotes',
    aguardandoComprador:  'Waiting for buyer',
    aprovadoresLabel:     'Approvers',
    aprovadoStatus:       'Approved',
    aguardandoStatus:     'Waiting',
    urgente:              'Urgent',
    economiaLabel:        'Savings',
    reabertoDe:           'Reopened from',
    reabertoComo:         'Reopened as',

    // Order detail — modal labels
    confirmarCompra:           'Confirm purchase',
    fornecedorLabel:           'Supplier',
    valorFinalLabel:           'Final value',
    condicaoPagLabel:          'Payment terms',
    dataCompraLabel:           'Purchase date',
    numParcelasLabel:          'Number of installments',
    vencimentoPrimeiraLabel:   '1st installment due date',
    selecionar:                'Select…',
    especifique:               'Specify',
    especifiquePlaceholder:    'Describe the reason…',
    justReaberturaLabel:       'Reopening justification',
    justReaberturaPlaceholder: 'Explain what changed or why you are reopening this order…',
    reabrirDescricao:          'A new order will be created as Requested with this order\'s data, linked to the original. This order remains as Rejected.',
    btnCancelar:               'Cancel',
    tituloReprovar:            'Reject order',
    tituloCancelar:            'Cancel order',
    tituloReabrir:             'Reopen order',

    // Toast / feedback messages — order detail
    pedidoNaoEncontrado:       'Order not found',
    pedidoRemovidoMsg:         'The order you tried to access does not exist or was removed.',
    semAcessoPedido:           'You do not have permission to access this order.',
    erroCarregarPedido:        'Failed to load order.',
    pedidoJaAssumido:          'Order was already claimed by another buyer.',
    pedidoAssumido:            'Order claimed!',
    erroAssumir:               'Failed to claim order.',
    pedidoLiberado:            'Order released to queue.',
    erroLiberarPedido:         'Failed to release order.',
    pedidoJaProcessado:        'This order was already processed by another approver.',
    pedidoAprovado:            'Order approved!',
    erroAprovar:               'Failed to approve.',
    selecionarMotivoSimples:   'Select a reason.',
    pedidoReprovado:           'Order rejected.',
    erroReprovar:              'Failed to reject.',
    compraRegistrada:          'Purchase registered!',
    erroRegistrarCompra:       'Failed to register purchase.',
    entregaConfirmada:         'Delivery confirmed!',
    erroConfirmarEntrega:      'Failed to confirm delivery.',
    pagamentoConfirmado:       'Payment confirmed!',
    erroConfirmarPagamento:    'Failed to confirm payment.',
    pedidoCanceladoMsg:        'Order cancelled.',
    erroCancelarPedido:        'Failed to cancel order.',
    pedidoAtualizado:          'Order updated!',
    erroSalvarAlteracoes:      'Failed to save changes.',
    erroEnviarComentario:      'Failed to send comment.',
    cotacaoIndicada:           'Quote selected!',
    erroIndicarCotacao:        'Failed to select quote.',
    pagamentoRegistrado:       'Payment registered!',
    erroRegistrarPagamento:    'Failed to register payment.',
    comprovanteAnexado:        'Receipt attached!',
    erroAnexarComprovante:     'Failed to attach receipt.',
    fornecedorValorObrig:      'Supplier and value are required.',
    cotacaoAdicionada:         'Quote added!',
    erroSalvarCotacao:         'Failed to save quote.',
    pdfExportado:              'PDF exported.',
    erroExportarPDF:           'Failed to export PDF. Check your connection.',
    informarJustificativa:     'Provide the reopening justification.',
    pedidoReabertoComo:        'Order reopened as',
    tipoNaoPermitido:          'File type not allowed. Use PDF, image (JPG/PNG/WebP), DOCX, or XLSX.',
    arquivoMuitoGrande:        'exceeds the 10 MB limit.',
    erroEnviarAnexo:           'Failed to upload: ',
    anexoRemovido:             'Attachment removed.',
    erroRemoverAnexo:          'Failed to remove: ',

    // Dashboard
    dashTotalGasto:       'Total spent in period',
    dashTotalPedidos:     'Total orders',
    dashAgAprovacao:      'Pending approval',
    dashAVencer:          'Installments due (7 days)',
    dashEconomia:         'Accumulated savings',
    dashEconomiaVs:       'Quotes vs. best price',
    dashExportar:         'Export',
    dashExportarExcel:    'Export Excel',
    dashExportarPDF:      'Export PDF',
    dashGastoPorEmpresa:  'Spend by company',
    dashProxParcelas:     'Upcoming installments',
    dashStatus:           'Order status',
    dashGastoPorCategoria:'Spend by category',
    dashGastoMensal:      'Monthly spend — last 6 months',
    dashEvolucaoGastos:   'Spending over time',
    dashPeriodo:          'Period',
    dashVisao:            'Financial and operational overview',
    semDados:             'No data for this period.',
    semUrgentes:          'No urgent orders',
    nenhumaParcela:       'No upcoming installments.',
    dashHoje:             'Today',
    periodoMes:           'This month',
    periodoTri:           'This quarter',
    periodoAno:           'This year',
    periodoLivre:         'Selected period',
    filtroPilulaMes:      'Month',
    filtroPilulaTri:      'Quarter',
    filtroPilulaAno:      'Year',
    filtroPilulaLivre:    'Custom',
    filtroPilulaAte:      'to',
    noPeriodo:            'In period',
    parcela:              'installment',
    parcelas:             'installments',
    parcelaNum:           'Installment',

    // Config
    configUsuarios:       'Users',
    configCadastros:      'Registries',
    configGeral:          'General',
    btnNovoUsuario:       'New user',
    btnNovaEmpresa:       'New company',
    btnNovaCategoria:     'New category',
    btnNovoFornecedor:    'New supplier',
    secaoEmpresas:        'Companies',
    secaoCategorias:      'Categories',
    secaoFornecedores:    'Suppliers',
    editarLabel:          'Edit',
    salvarLabel:          'Save',
    novoUsuarioTitulo:    'New user',
    editarUsuarioTitulo:  'Edit user',
    novaEmpresaTitulo:    'New company',
    editarEmpresaTitulo:  'Edit company',
    novaCategoriaTitulo:  'New category',
    editarCategoriaTitulo:'Edit category',
    editarFornTitulo:     'Edit supplier',
    nomeObrigatorio:      'Name is required.',
    emailObrigatorio:     'Email is required.',
    emailInvalido:        'Invalid email format.',
    perfilObrigatorio:    'Select a profile.',
    empresaObrigatoria:   'Link at least one company.',
    modoDemo:             'Changes are not allowed in demo mode.',
    usuarioAtualizado:    'User updated!',
    usuarioCriado:        'User created! Set the password in Firebase Authentication.',
    usuarioExcluido:      'User deleted.',
    empresaAtualizada:    'Company updated!',
    empresaCriada:        'Company created!',
    categoriaAtualizada:  'Category updated!',
    categoriaCriada:      'Category created!',
    fornecedorAtualizado: 'Supplier updated!',
    erroSalvar:           'Failed to save.',
    semEmpresas:           'No companies registered.',
    semFornecedores:       'No suppliers registered.',
    empresaAtivaLabel:     'Active',
    empresaInativaLabel:   'Inactive',
    cnpjNaoInformado:      'CNPJ not provided',
    categoriaPadraoLabel:  'Default',
    catPersonalizadaLabel: 'Custom',
    usosPedido:            'order',
    usosPedidos:           'orders',
    erroExcluir:          'Failed to delete.',
    configGeral:           'General',
    demoTitulo:            'Demo data',
    demoDesc:              'Resets all orders, quotes, and history in the demo environment to the default sample data. This action deletes current data and cannot be undone.',
    btnResetarDemo:        'Reset demo data',
    demoAguarde:           'Please wait…',
    demoResetadoMsg:       'Demo data reset successfully!',
    demoErroReset:         'Failed to reset demo data.',
    confirmarResetDemo:    'This will delete all orders and recreate the sample data. Continue?',
    tourTitulo:            'Guided tour',
    tourDesc:              'Review the welcome tour that introduces the main features of the system.',
    btnVerTour:            'Start tour',
    erroMarcarLidas:       'Could not mark notifications as read.',
    erroMarcarLida:        'Could not mark notification as read.',
    novaNotificacao:       'New notification',
    erroAcessarDemo:       'Failed to access demo mode. Please try again.',
    erroEnviarEmail:       'Failed to send email. Check the address.',
    erroSair:              'Failed to sign out. Please try again.',
    recuperarSenha:        'Reset password',
    entrando:              'Signing in…',

    // Offline / errors
    semConexao:           'Offline · changes will be sent when connection is restored.',
    conexaoRestabelecida: 'Connection restored.',
    erroCarregar:         'Failed to load. Check your connection.',
    semAcesso:            'No access',
    semAcessoMsg:         'You do not have permission to view this order, or it does not exist.',

    // Tour
    tourStep1Titulo:  'Order board',
    tourStep1Desc:    'Here are all orders, organized by stage in the purchasing flow.',
    tourStep2Titulo:  'New order',
    tourStep2Desc:    'Create a purchase order in seconds. Fill in what you need and submit for approval.',
    tourStep3Titulo:  'Notifications',
    tourStep3Desc:    'Stay informed of everything that changes in your orders — approvals, rejections, and mentions.',
    tourStep4Titulo:  'Appearance',
    tourStep4Desc:    'Choose the look you prefer: dark or light mode.',
    tourStep5Titulo:  'Settings',
    tourStep5Desc:    'Manage users, companies, and categories of the system.',
    tourPular:        'Skip tour',
    tourProximo:      'Next',
    tourConcluir:     'Done',

    // Topbar / nav
    navPedidos:             'Orders',
    navRelatorios:          'Reports',
    navConfiguracoes:       'Settings',
    navSair:                'Sign out',
    tooltipPaleta:          'Command palette (Ctrl+K)',
    tooltipNotificacoes:    'Notifications',
    tooltipFecharConfig:    'Close settings',
    tooltipSair:            'Sign out',
    tooltipMenu:            'Menu',
    confirmarSair:          'Sign out?',

    // Pluralizáveis
    selecionado:      'selected',
    selecionados:     'selected',
    pedidoExportado:  'order exported',
    pedidosExportados:'orders exported',
    pedidoCancelado:  'order cancelled',
    pedidosCancelados:'orders cancelled',

    // Erros / feedback
    confirmarCancelamento: 'Confirm cancellation',
    motivoLabel:           'Reason',
    motivoPlaceholder:     'Select reason…',
    motivoOutros:          'Describe the reason',
    erroCarregarPedidos:   'Could not load orders',
    verificarConexao:      'Check your connection and reload the page.',
    erroCamposObrigatorios:'Please fill in all required fields.',
    bulkNenhumCancelavel:  'No selected order can be cancelled with your profile.',
    selecionarMotivo:      'Select a cancellation reason.',
    descreverMotivo:       'Describe the reason.',
    erroCancelarPedidos:   'Error cancelling orders: ',
    seraoCancelados:       'will be cancelled',
  },
}

export function t(chave, lang) {
  const idioma = lang || sessionStorage.getItem('praxis_lang') || 'pt'
  return TRADUCOES[idioma]?.[chave] ?? chave
}

export const KANBAN_COLUNAS = [
  STATUS.SOLICITADO,
  STATUS.AG_COTACAO,
  STATUS.EM_APROVACAO,
  STATUS.APROVADO,
  STATUS.COMPRADO,
  STATUS.ENTREGUE,
  STATUS.PAGO,
]

export const STORAGE_PATHS = {
  cotacao:     (pedidoId, cotacaoId) => `pedidos/${pedidoId}/cotacoes/${cotacaoId}`,
  comprovante: (pedidoId, parcelaId) => `pedidos/${pedidoId}/comprovantes/${parcelaId}`,
  anexo:       (pedidoId)            => `pedidos/${pedidoId}/anexos`,
}
