export const STATUS = {
  SOLICITADO:   'solicitado',
  AG_COTACAO:   'ag_cotacao',
  EM_APROVACAO: 'em_aprovacao',
  APROVADO:     'aprovado',
  COMPRADO:     'comprado',
  ENTREGUE:     'entregue',
  PAGO:         'pago',
  REPROVADO:    'reprovado',
  CANCELADO:    'cancelado',
}

export const STATUS_LABEL = {
  solicitado:   'Solicitado',
  ag_cotacao:   'Em cotação',
  em_aprovacao: 'Em aprovação',
  aprovado:     'Aprovado',
  comprado:     'Comprado',
  entregue:     'Entregue',
  pago:         'Pago',
  reprovado:    'Reprovado',
  cancelado:    'Cancelado',
}

export const STATUS_COLOR = {
  solicitado:   'neutral',
  ag_cotacao:   'blue',
  em_aprovacao: 'gold',
  aprovado:     'green',
  comprado:     'green',
  entregue:     'green',
  pago:         'green',
  reprovado:    'red',
  cancelado:    'red',
}

export const STATUS_DOT_COLOR = {
  solicitado:   'dot-gray',
  ag_cotacao:   'dot-blue',
  em_aprovacao: 'dot-gold',
  aprovado:     'dot-green',
  comprado:     'dot-green',
  entregue:     'dot-green',
  pago:         'dot-green',
  reprovado:    'dot-red',
  cancelado:    'dot-red',
}

export const PERFIS = {
  SUPREMO:     'supremo',
  GESTOR:      'gestor',
  APROVADOR:   'aprovador',
  COMPRADOR:   'comprador',
  FINANCEIRO:  'financeiro',
  SOLICITANTE: 'solicitante',
}

export const PERFIS_LABEL = {
  supremo:     'Supremo',
  gestor:      'Gestor',
  aprovador:   'Aprovador',
  comprador:   'Comprador',
  financeiro:  'Financeiro',
  solicitante: 'Solicitante',
}

export const PERFIS_COLOR = {
  supremo:     'gold',
  gestor:      'green',
  aprovador:   'blue',
  comprador:   'neutral',
  financeiro:  'neutral',
  solicitante: 'neutral',
}

export const MOTIVOS_REPROVACAO = [
  'Valor acima do orçamento',
  'Cotações insuficientes',
  'Justificativa inadequada',
  'Fornecedor não aprovado',
  'Outros',
]

export const MOTIVOS_CANCELAMENTO = [
  'Compra não necessária',
  'Fornecedor indisponível',
  'Erro no pedido',
  'Pedido duplicado',
  'Outros',
]

// Paleta das categorias: os tons quentes de cerâmica e afresco que os relatórios
// usam (variáveis --rel-* em views.css). O que fica gravado é o hex canônico do
// tom; qualquer outra cor (cadastros antigos, escolha à mão) é levada ao tom mais
// próximo, para a categoria ter a mesma cor em toda parte.
export const TONS_CATEGORIA = {
  ocre: '#D3A04E', areia: '#C9B48C', oliva: '#93AE7C', mar: '#82ADA3', egeu: '#8CA6C2',
  ametista: '#A893BC', rosa: '#C88E96', vinho: '#B9746B', argila: '#A09282',
}
export const CORES_CATEGORIA = Object.values(TONS_CATEGORIA)
export function tomDaCor(hex) {
  const c = String(hex || '').trim().toUpperCase()
  const exato = Object.keys(TONS_CATEGORIA).find(k => TONS_CATEGORIA[k].toUpperCase() === c)
  if (exato) return exato
  const m = /^#?([0-9A-F]{6})$/.exec(c)
  if (!m) return null
  const n = parseInt(m[1], 16)
  const r = (n >> 16) / 255, g = ((n >> 8) & 255) / 255, b = (n & 255) / 255
  const max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min
  const l = (max + min) / 2
  const s = d === 0 ? 0 : d / (1 - Math.abs(2 * l - 1))
  if (s < 0.16) return 'argila'
  let h = max === r ? ((g - b) / d) % 6 : max === g ? (b - r) / d + 2 : (r - g) / d + 4
  h = (h * 60 + 360) % 360
  if (h < 18 || h >= 345) return 'vinho'
  if (h < 46) return 'ocre'
  if (h < 70) return 'areia'
  if (h < 165) return 'oliva'
  if (h < 200) return 'mar'
  if (h < 255) return 'egeu'
  if (h < 300) return 'ametista'
  return 'rosa'
}
export function corCategoria(cor) {
  return TONS_CATEGORIA[tomDaCor(cor) || 'argila']
}

export const CATEGORIAS_PADRAO = [
  { nome: 'Manutenção',       cor: '#B9746B' },
  { nome: 'Escritório',       cor: '#8CA6C2' },
  { nome: 'Operacional',      cor: '#C9B48C' },
  { nome: 'Alimentação',      cor: '#93AE7C' },
  { nome: 'Uniformes e EPIs', cor: '#A893BC' },
  { nome: 'Marketing',        cor: '#D3A04E' },
  { nome: 'TI',               cor: '#82ADA3' },
  { nome: 'Serviços',         cor: '#A09282' },
]

export const EVENTOS = {
  PEDIDO_URGENTE:        'pedido_urgente',
  AG_COTACAO:            'ag_cotacao',
  COMPRADOR_ASSUMIU:     'comprador_assumiu',
  COTACOES_PRONTAS:      'cotacoes_prontas',
  PEDIDO_APROVADO:       'pedido_aprovado',
  PEDIDO_REPROVADO:      'pedido_reprovado',
  PEDIDO_CANCELADO:      'pedido_cancelado',
  PEDIDO_COMPRADO:       'pedido_comprado',
  PEDIDO_ENTREGUE:       'pedido_entregue',
  PARCELA_VENCENDO:      'parcela_vencendo',
  PARCELA_VENCIDA:       'parcela_vencida',
  MENCAO_COMENTARIO:     'mencao_comentario',
  PEDIDO_PARADO:         'pedido_parado',
  PEDIDO_ENTREGUE_SOLIC: 'pedido_entregue_solic',
}

export const EVENTOS_ICON_CLASS = {
  pedido_urgente:        'notif-icon-red',
  ag_cotacao:            'notif-icon-blue',
  comprador_assumiu:     'notif-icon-gold',
  cotacoes_prontas:      'notif-icon-blue',
  pedido_aprovado:       'notif-icon-green',
  pedido_reprovado:      'notif-icon-red',
  pedido_cancelado:      'notif-icon-red',
  pedido_comprado:       'notif-icon-green',
  pedido_entregue:       'notif-icon-green',
  parcela_vencendo:      'notif-icon-gold',
  parcela_vencida:       'notif-icon-red',
  mencao_comentario:     'notif-icon-gold',
  pedido_parado:         'notif-icon-gold',
  pedido_entregue_solic: 'notif-icon-green',
}

export const UNIDADES = [
  'un', 'cx', 'kg', 'L', 'm', 'm²', 'm³',
  'par', 'pct', 'kit', 'rolo', 'saco',
  'hora', 'mês', 'pessoa', 'licença', 'serviço',
]

export const CONDICAO_PAGAMENTO = {
  antecipado:         'Antecipado',
  apos_recebimento:   'Após recebimento',
}

// ── Traduções ────────────────────────────────────────────────
export const TRADUCOES = {
  pt: {
    // Login / auth
    titulo:           'Pedidos',
    relatorios:       'Relatórios',
    configuracoes:    'Configurações',
    btnEntrar:        'Entrar',
    btnDemo:          'Acessar modo demo',
    tagline:          'Gestão de compras corporativas',
    emailLabel:       'E-mail',
    senhaLabel:       'Senha',
    esqueci:          'Esqueci a senha',
    escolherIdioma:   'Escolha o idioma do demo',
    continuar:        'Continuar',
    voltar:           'Voltar',
    novoPedido:       'Novo pedido',
    todos:            'Todos',
    urgentes:         'Urgentes',
    meusPedidos:      'Meus pedidos',
    estaSemana:       'Esta semana',
    encerrados:       'Encerrados',
    resetEnviado:     'Confira seu e-mail',
    resetMsg:         'Verifique sua caixa de entrada e siga as instruções para redefinir sua senha.',
    emailReset:       'Informe o e-mail da sua conta. Enviaremos um link para você criar uma nova senha.',
    enviarLink:       'Enviar link',
    loginTitulo:      'Toda compra tem um caminho.',
    loginTitulo2:     'Do pedido ao pagamento.',
    loginTexto:       'Quem pede, quem cota, quem aprova e quem paga. Sete etapas, cada uma com responsável, prazo e histórico.',
    loginCardTitulo:  'Acesse sua conta',
    loginCardSub:     'Use o e-mail cadastrado pela sua empresa.',
    demoDica:         'Dados fictícios, sem cadastro.',
    mostrarSenha:     'Mostrar senha',
    ocultarSenha:     'Ocultar senha',
    alternarTema:     'Alternar tema claro e escuro',
    voltarLogin:      'Voltar para o login',
    resetMsgPara:     'Se houver uma conta para {email}, você vai receber um link para criar uma nova senha. Confira também a caixa de spam.',
    preenchaCampos:   'Informe e-mail e senha.',
    informeEmail:     'Informe seu e-mail.',
    loginEtapas:      'Pedido|Cotação|Aprovação|Aprovado|Compra|Entrega|Pagamento',

    // Shared UI
    fechar:           'Fechar',
    cancelar:         'Cancelar',
    salvar:           'Salvar',
    confirmar:        'Confirmar',
    editar:           'Editar',
    excluir:          'Excluir',
    selecionar:       'Selecionar…',
    opcional:         'Opcional',
    limpar:           'Limpar',

    // Topbar tooltips
    tooltipTema:      'Alternar tema',
    tooltipNotif:     'Notificações',
    tooltipConfig:    'Configurações',
    tooltipCmd:       'Paleta de comandos (Ctrl+K)',

    // Pedidos toolbar / pills
    meusPendentes:    'Meus pendentes',
    buscarPedido:     'Buscar pedido…',
    salvarVisao:      'Salvar visão',
    periodo:          'Período:',

    // List filters & columns
    todasEmpresas:    'Todas as empresas',
    todasCategorias:  'Todas as categorias',
    TodosCompradores: 'Todos os compradores',
    limparFiltros:    'Limpar filtros',
    colPedido:        'Pedido',
    colEmpresa:       'Empresa',
    colSolicitante:   'Solicitante',
    colValorEst:      'Valor est.',
    colData:          'Data',
    paginaAnt:        'Anterior',
    paginaProx:       'Próxima',

    // Kanban empty states
    semPedidosColuna: 'Sem pedidos aqui',
    nenhumResultado:  'Nenhum resultado encontrado',
    nenhumPedido:     'Nenhum pedido por aqui ainda',
    ajustarFiltro:    'Tente ajustar o filtro ou o termo de busca.',
    abrirPrimeiro:    'Abra o primeiro pedido clicando em "Novo pedido".',

    // New order modal
    npTitulo:           'Título',
    npTituloPlaceholder:'Ex: Caixa de luvas descartáveis',
    npEmpresa:          'Empresa',
    npQuantidade:       'Quantidade',
    npUnidade:          'Unidade',
    npData:             'Necessário até',
    npValor:            'Valor estimado',
    npCC:               'Centro de custo',
    npCategoria:        'Categoria',
    npUrgente:          'Pedido urgente',
    npObs:              'Observações',
    npObsPlaceholder:   'Descreva detalhes relevantes para a compra…',
    btnAbrirPedido:     'Abrir pedido',
    duplicarPedido:     'Duplicar pedido',

    // Saved views
    nomeVisao:          'Nome da visão',
    nomeVisaoPlaceholder:'Ex: Urgentes da semana',

    // Bulk actions
    exportarCSV:          'Exportar CSV',
    cancelarSelecionados: 'Cancelar selecionados',
    desmarcarTudo:        'Desmarcar tudo',

    // Order detail — action buttons
    btnExportarPDF:       'Exportar PDF',
    btnDuplicar:          'Duplicar',
    btnReabrir:           'Reabrir pedido',
    btnCancelarPedido:    'Cancelar pedido',
    btnAssumirPedido:     'Assumir pedido',
    btnLiberarPedido:     'Liberar pedido',
    btnAprovar:           'Aprovar',
    btnReprovar:          'Reprovar',
    btnExecutarCompra:    'Registrar compra',
    btnConfirmarEntrega:  'Confirmar entrega',
    btnConfirmarPagamento:'Confirmar pagamento',
    btnEditarPedido:      'Editar pedido',

    // Order detail — sections & UI
    secaoAnexos:          'Anexos',
    secaoAtividade:       'Atividade',
    secaoCotacoes:        'Cotações',
    secaoParcelas:        'Parcelas',
    btnAdicionarAnexo:    'Adicionar',
    btnComparar:          'Comparar',
    btnNovaCotacao:       'Nova cotação',
    btnAdicionarParcela:  'Adicionar parcela',
    btnEnviarComentario:  'Enviar',
    placeholderComentario:'Comentar… use @ para mencionar',

    // Order detail — meta labels & people
    metaEmpresa:          'Empresa',
    metaQtd:              'Quantidade',
    metaCategoria:        'Categoria',
    metaNecessario:       'Necessário até',
    metaValorEst:         'Valor estimado',
    metaCentro:           'Centro de custo',
    metaValorFinal:       'Valor final',
    metaDataCompra:       'Data da compra',
    metaDataEntrega:      'Data de entrega',
    pessoasEnvolvidas:    'Pessoas envolvidas',
    solicitanteLabel:     'Solicitante',
    criouPedido:          'Criou o pedido',
    compradorLabel:       'Comprador',
    semCotacoes:          'Sem cotações',
    aguardandoComprador:  'Aguardando comprador',
    aprovadoresLabel:     'Aprovadores',
    aprovadoStatus:       'Aprovado',
    aguardandoStatus:     'Aguardando',
    urgente:              'Urgente',
    economiaLabel:        'Economia',
    reabertoDe:           'Reaberto a partir de',
    reabertoComo:         'Reaberto como',

    // Order detail — modal labels
    confirmarCompra:           'Confirmar compra',
    fornecedorLabel:           'Fornecedor',
    valorFinalLabel:           'Valor final',
    condicaoPagLabel:          'Condição de pagamento',
    dataCompraLabel:           'Data da compra',
    numParcelasLabel:          'Número de parcelas',
    vencimentoPrimeiraLabel:   'Vencimento da 1ª parcela',
    selecionar:                'Selecionar…',
    especifique:               'Especifique',
    especifiquePlaceholder:    'Descreva o motivo…',
    justReaberturaLabel:       'Justificativa de reabertura',
    justReaberturaPlaceholder: 'Explique o que mudou ou por que está reabrindo este pedido…',
    reabrirDescricao:          'Um novo pedido será criado em Solicitado com os dados deste, vinculado ao original. Este pedido continua como Reprovado.',
    btnCancelar:               'Cancelar',
    tituloReprovar:            'Reprovar pedido',
    tituloCancelar:            'Cancelar pedido',
    tituloReabrir:             'Reabrir pedido',

    // Toast / feedback messages — order detail
    pedidoNaoEncontrado:       'Pedido não encontrado',
    pedidoRemovidoMsg:         'O pedido que você tentou acessar não existe ou foi removido.',
    semAcessoPedido:           'Você não tem permissão para acessar este pedido.',
    erroCarregarPedido:        'Erro ao carregar pedido.',
    pedidoJaAssumido:          'Pedido já foi assumido por outro comprador.',
    pedidoAssumido:            'Pedido assumido. Você é o comprador responsável.',
    erroAssumir:               'Erro ao assumir pedido.',
    pedidoLiberado:            'Pedido liberado para a fila.',
    erroLiberarPedido:         'Erro ao liberar pedido.',
    pedidoJaProcessado:        'Este pedido já foi processado por outro aprovador.',
    pedidoAprovado:            'Pedido aprovado.',
    erroAprovar:               'Erro ao aprovar.',
    selecionarMotivoSimples:   'Selecione um motivo.',
    pedidoReprovado:           'Pedido reprovado.',
    erroReprovar:              'Erro ao reprovar.',
    compraRegistrada:          'Compra registrada.',
    erroRegistrarCompra:       'Erro ao registrar compra.',
    entregaConfirmada:         'Entrega confirmada.',
    erroConfirmarEntrega:      'Erro ao confirmar entrega.',
    pagamentoConfirmado:       'Pagamento confirmado. Pedido concluído.',
    erroConfirmarPagamento:    'Erro ao confirmar pagamento.',
    pedidoCanceladoMsg:        'Pedido cancelado.',
    erroCancelarPedido:        'Erro ao cancelar pedido.',
    pedidoAtualizado:          'Pedido atualizado.',
    erroSalvarAlteracoes:      'Erro ao salvar alterações.',
    erroEnviarComentario:      'Erro ao enviar comentário.',
    cotacaoIndicada:           'Cotação indicada. O pedido seguiu para aprovação.',
    erroIndicarCotacao:        'Erro ao indicar cotação.',
    pagamentoRegistrado:       'Pagamento registrado.',
    erroRegistrarPagamento:    'Erro ao registrar pagamento.',
    comprovanteAnexado:        'Comprovante anexado.',
    erroAnexarComprovante:     'Erro ao anexar comprovante.',
    fornecedorValorObrig:      'Fornecedor e valor são obrigatórios.',
    cotacaoAdicionada:         'Cotação registrada.',
    erroSalvarCotacao:         'Erro ao salvar cotação.',
    pdfExportado:              'PDF exportado.',
    erroExportarPDF:           'Erro ao exportar PDF. Verifique a conexão.',
    informarJustificativa:     'Informe a justificativa de reabertura.',
    pedidoReabertoComo:        'Pedido reaberto como',
    tipoNaoPermitido:          'Tipo não permitido. Use PDF, imagem (JPG/PNG/WebP), DOCX ou XLSX.',
    arquivoMuitoGrande:        'excede o limite de 10 MB.',
    erroEnviarAnexo:           'Erro ao enviar: ',
    anexoRemovido:             'Anexo removido.',
    erroRemoverAnexo:          'Erro ao remover: ',

    // Detalhe do pedido — redesenho (painel de decisão, régua, seções)
    dtFechar:                  'Fechar',
    dtMaisAcoes:               'Mais ações',
    dtDadosPedido:             'Dados do pedido',
    dtDescricao:               'Descrição',
    dtComparadasIndicada:      'Diferença para a indicada',
    dtComparadasMenor:         'Diferença para a de menor valor',
    dtLadoALadoTitulo:         'Cotações lado a lado',
    dtLadoALado:               'Lado a lado',
    dtComentario:              'Comentário',
    dtComentarioPlaceholder:   'Escreva um comentário',
    dtMenciona:                'menciona',
    dtEnvia:                   'envia',
    dtComentar:                'Comentar',
    dtAnexar:                  'Anexar',
    dtReprovarIntro:           'O pedido volta ao solicitante com o motivo informado. Ele poderá reabri-lo com ajustes.',
    dtCancelarIntro:           'O pedido sai do fluxo e fica registrado como cancelado. Essa ação não pode ser desfeita.',
    dtVoltar:                  'Voltar',
    dtPropostaIndicada:        'Proposta indicada',
    dtCotacaoIndicada:         'Cotação indicada',
    dtNomeFornecedor:          'Nome do fornecedor',
    dtRegistrarCotacao:        'Registrar cotação',
    dtRegistrarPagamento:      'Registrar pagamento',
    dtDuplicarPedido:          'Duplicar pedido',
    dtProximoPasso:            'Próximo passo',
    dtComVoce:                 'Com você',
    dtAcoesDoPasso:            'Ações deste passo',
    dtResponsavel:             'Responsável',
    dtPrazo:                   'Prazo',
    dtSemResponsavel:          'Ainda sem comprador',
    dtCompradorDesignado:      'Comprador designado',
    dtAprovadoresEmpresa:      'Aprovadores da empresa',
    dtEquipeFinanceira:        'Equipe financeira',
    dtRecebimento:             'Recebimento',
    dtSolicTituloPode:         'Assuma o pedido para começar as cotações',
    dtSolicTitulo:             'Aguardando um comprador',
    dtSolicTextoPode:          'Quem assume fica responsável por reunir as propostas e indicar a melhor.',
    dtSolicTexto:              'Assim que um comprador assumir o pedido, as cotações começam.',
    dtCotTituloVazio:          'Registre as cotações',
    dtCotTituloAndamento:      'Cotação em andamento',
    dtCotTituloIndicar:        'Indique a melhor proposta',
    dtCotTextoOutros:          'O comprador está reunindo propostas de fornecedores.',
    dtCotTextoVazio:           'Reúna ao menos três propostas e indique a melhor para enviar à aprovação.',
    dtCotTextoPoucas:          'Registre mais propostas ou indique a melhor na lista de cotações para enviar à aprovação.',
    dtCotTextoIndicar:         'Indicar uma proposta na lista de cotações envia o pedido à aprovação.',
    dtMenorValor:              'Menor valor',
    dtAprovTituloPode:         'Aguardando sua decisão',
    dtAprovTitulo:             'Em análise pelo aprovador',
    dtFoiIndicada:             'foi a proposta indicada',
    dtEntre:                   'entre',
    dtCotacoesMin:             'cotações',
    dtAprovSemIndicada:        'O pedido está com o aprovador.',
    dtFrenteEstimado:          'Frente ao estimado',
    dtFrenteMaisCara:          'frente à proposta mais cara',
    dtAprovadoTituloPode:      'Registre a compra',
    dtAprovadoTitulo:          'Aprovado, aguardando a compra',
    dtAprovadoTextoPode:       'Informe o fornecedor, o valor final e as parcelas.',
    dtAprovadoTexto:           'O comprador registra a compra com o fornecedor.',
    dtValorAprovado:           'Valor aprovado',
    dtCompradoTituloPode:      'Confirme a entrega quando chegar',
    dtCompradoTitulo:          'Aguardando a entrega',
    dtCompradoTexto:           'Confira o item e confirme o recebimento. Depois o financeiro acompanha o pagamento.',
    dtEntregueTitulo:          'Entregue, aguardando pagamento',
    dtEntregueTituloConcluir:  'Conclua o pagamento',
    dtSemParcelas:             'Sem parcelas registradas.',
    dtPago:                    'Pago',
    dtParcela:                 'Parcela',
    dtConcluido:               'Concluído',
    dtPagoTitulo:              'Pedido concluído',
    dtValorPago:               'Valor pago',
    dtConcluidoEm:             'Concluído em',
    dtDoPedidoAoPagamento:     'Do pedido ao pagamento',
    dtReprovado:               'Reprovado',
    dtReprovadoTitulo:         'Pedido reprovado',
    dtJaReaberto:              'Já foi reaberto como',
    dtDicaReabrir:             'Para tentar de novo com ajustes, use Reabrir pedido no menu de ações.',
    dtCancelado:               'Cancelado',
    dtCanceladoTitulo:         'Pedido cancelado',
    dtCanceladoTexto:          'O pedido saiu do fluxo de compras.',
    dtCotVazioTitulo:          'Nenhuma cotação ainda',
    dtCotVazioPode:            'Registre ao menos três propostas para comparar e enviar à aprovação.',
    dtCotVazioSolic:           'As propostas aparecem aqui depois que um comprador assumir o pedido.',
    dtCotVazioOutros:          'Nenhuma proposta foi registrada para este pedido.',
    dtIndicada:                'Indicada',
    dtBaseComparacao:          'Base',
    dtMaisBarataQueIndicada:   'Mais barata que a proposta indicada',
    dtAbrirArquivo:            'Abrir arquivo',
    dtAbrirArquivoCotacao:     'Abrir arquivo da cotação',
    dtIndicar:                 'Indicar',
    dtIndicarTitulo:           'Indicar esta proposta e enviar o pedido para aprovação',
    dtIndicarConfirmaTitulo:   'Indicar e enviar para aprovação?',
    dtIndicarConfirmaTexto:    'O pedido segue para o aprovador com esta proposta.',
    dtIndicarConfirmaOk:       'Indicar e enviar',
    dtSemCondicoes:            'Sem condições informadas',
    dtEconomiaFrase1:          'A indicada fica',
    dtEconomiaFrase2:          'abaixo da proposta mais cara.',
    dtAtividadeVazia:          'Nenhuma atividade ainda',
    dtAtividadeVaziaTexto:     'Mudanças de etapa, comentários e anexos aparecem aqui.',
    dtPagosDe:                 'pagos de',
    dtPercentualPago:          'Percentual pago',
    dtPagar:                   'Pagar',
    dtVerComprovante:          'Ver comprovante',
    dtAnexarComprovante:       'Anexar comprovante',
    dtAnexosVazio:             'Nenhum anexo',
    dtAnexosVazioTexto:        'Especificações, fotos de referência e documentos de apoio ficam aqui.',
    dtTempoPorEtapa:           'Tempo por etapa',
    dtAteAgora:                'até agora',
    dtAgora:                   'agora',

    // Dashboard
    dashTotalGasto:       'Total gasto no período',
    dashTotalPedidos:     'Total de pedidos',
    dashAgAprovacao:      'Ag. aprovação',
    dashAVencer:          'Parcelas a vencer (7 dias)',
    dashEconomia:         'Economia acumulada',
    dashEconomiaVs:       'Cotações vs. melhor preço',
    dashExportar:         'Exportar',
    dashExportarExcel:    'Exportar Excel',
    dashExportarPDF:      'Exportar PDF',
    dashGastoPorEmpresa:  'Gasto por empresa',
    dashProxParcelas:     'Próximas parcelas',
    dashStatus:           'Status dos pedidos',
    dashGastoPorCategoria:'Gasto por categoria',
    dashGastoMensal:      'Gasto mensal — últimos 6 meses',
    dashEvolucaoGastos:   'Evolução de gastos',
    dashPeriodo:          'Período',
    dashVisao:            'Visão financeira e operacional',
    semDados:             'Sem dados no período.',
    semUrgentes:          'Sem urgentes',
    nenhumaParcela:       'Nenhuma parcela a vencer.',
    dashHoje:             'Hoje',
    periodoMes:           'Este mês',
    periodoTri:           'Este trimestre',
    periodoAno:           'Este ano',
    periodoLivre:         'Período selecionado',
    filtroPilulaMes:      'Mês',
    filtroPilulaTri:      'Trimestre',
    filtroPilulaAno:      'Ano',
    filtroPilulaLivre:    'Livre',
    filtroPilulaAte:      'até',
    noPeriodo:            'No período',
    parcela:              'parcela',
    parcelas:             'parcelas',
    parcelaNum:           'Parcela',

    // Config
    configUsuarios:       'Usuários',
    btnNovoUsuario:       'Novo usuário',
    btnNovaEmpresa:       'Nova empresa',
    btnNovaCategoria:     'Nova categoria',
    secaoEmpresas:        'Empresas',
    secaoCategorias:      'Categorias',
    secaoFornecedores:    'Fornecedores',
    editarLabel:          'Editar',
    salvarLabel:          'Salvar',
    novoUsuarioTitulo:    'Novo usuário',
    editarUsuarioTitulo:  'Editar usuário',
    novaEmpresaTitulo:    'Nova empresa',
    editarEmpresaTitulo:  'Editar empresa',
    novaCategoriaTitulo:  'Nova categoria',
    editarCategoriaTitulo:'Editar categoria',
    editarFornTitulo:     'Editar fornecedor',
    nomeObrigatorio:      'Nome é obrigatório.',
    emailObrigatorio:     'E-mail é obrigatório.',
    emailInvalido:        'E-mail em formato inválido.',
    perfilObrigatorio:    'Selecione um perfil.',
    empresaObrigatoria:   'Vincule pelo menos uma empresa.',
    modoDemo:             'No modo demonstração as alterações não são salvas.',
    usuarioAtualizado:    'Usuário atualizado.',
    usuarioCriado:        'Usuário criado. Defina a senha de acesso no Firebase Authentication.',
    empresaAtualizada:    'Empresa atualizada.',
    empresaCriada:        'Empresa criada.',
    categoriaAtualizada:  'Categoria atualizada.',
    categoriaCriada:      'Categoria criada.',
    fornecedorAtualizado: 'Fornecedor atualizado.',
    erroSalvar:           'Erro ao salvar.',
    erroExcluir:          'Erro ao excluir.',
    cnpjNaoInformado:      'CNPJ não informado',
    categoriaPadraoLabel:  'Padrão',
    catPersonalizadaLabel: 'Personalizada',
    usosPedido:            'pedido',
    usosPedidos:           'pedidos',
    btnResetarDemo:        'Redefinir dados',
    demoResetadoMsg:       'Dados de exemplo redefinidos.',
    demoErroReset:         'Não foi possível redefinir os dados de exemplo.',
    confirmarResetDemo:    'Redefinir dados de exemplo?',
    tourTitulo:            'Tour de apresentação',
    tourDesc:              'Reveja o tour de boas-vindas que apresenta os principais recursos do sistema.',
    btnVerTour:            'Ver tour',
    // Configurações (passada de acabamento)
    cfgAtivos:              'Ativos',
    cfgInativos:            'Inativos',
    cfgAtivo:               'Ativo',
    cfgInativo:             'Inativo',
    cfgAtiva:               'Ativa',
    cfgInativa:             'Inativa',
    cfgFiltrarStatus:       'Filtrar por status',
    cfgBuscarUsuario:       'Buscar por nome ou e-mail',
    cfgColUsuario:          'Usuário',
    cfgColPerfil:           'Perfil',
    cfgColEmpresas:         'Empresas',
    cfgColUltimoAcesso:     'Último acesso',
    cfgColStatus:           'Status',
    cfgColAcoes:            'Ações',
    cfgColCategoria:        'Categoria',
    cfgColTipo:             'Tipo',
    cfgColPedidos:          'Pedidos',
    cfgColFornecedor:       'Fornecedor',
    cfgColValor:            'Valor',
    cfgTodasEmpresasTxt:    'Todas as empresas',
    cfgNenhuma:             'Nenhuma',
    cfgSemAcessoDica:       'Nenhum acesso registrado ainda',
    cfgNunca:               'Nunca',
    cfgAgora:               'Agora',
    cfgHoje:                'Hoje',
    cfgOntem:               'Ontem',
    cfgVoce:                'Você',
    cfgNovoCurto:           'Novo',
    cfgNovaCurto:           'Nova',
    cfgUsuarioSing:         'usuário',
    cfgUsuarioPlur:         'usuários',
    cfgInativoSing:         'inativo',
    cfgInativoPlur:         'inativos',
    cfgTodosAtivos:         'todos ativos',
    cfgUsuariosDesc:        'O perfil define o que cada um pode fazer.',
    cfgInativaSing:         'inativa',
    cfgInativaPlur:         'inativas',
    cfgCriadaEquipeSing:    'criada pela equipe',
    cfgCriadaEquipePlur:    'criadas pela equipe',
    cfgNadaEmAberto:        'Nada em aberto',
    cfgEmpresaSing:         'empresa',
    cfgEmpresaPlur:         'empresas',
    cfgCategoriaSing:       'categoria',
    cfgCategoriaPlur:       'categorias',
    cfgFornecedorSing:      'fornecedor',
    cfgFornecedorPlur:      'fornecedores',
    cfgSemResultadoTitulo:  'Nenhum resultado',
    cfgSemResultadoBusca:   'Nada corresponde a “{q}”. Confira a grafia ou tente outro termo.',
    cfgSemInativosTitulo:   'Nenhum usuário inativo',
    cfgSemInativosSub:      'Usuários desativados aparecem aqui e podem ser reativados quando precisar.',
    cfgSemUsuariosTitulo:   'Nenhum usuário',
    cfgSemUsuariosSub:      'Cadastre a equipe para começar a registrar pedidos.',
    cfgLimparBusca:         'Limpar busca',
    cfgVerTodos:            'Ver todos',
    cfgEditarX:             'Editar {nome}',
    cfgNome:                'Nome',
    cfgEmail:               'E-mail',
    cfgNomeCompleto:        'Nome completo',
    cfgEmailFixo:           'O e-mail é o login e não pode ser alterado.',
    cfgAcesso:              'Acesso',
    cfgSelecionarTodas:     'Selecionar todas',
    cfgLimparSelecao:       'Limpar',
    cfgSomenteSupremo:      'Somente um usuário Supremo pode alterar outro Supremo.',
    cfgNaoDesativarVoce:    'Você não pode desativar o próprio acesso.',
    cfgDesativarTitulo:     'Desativar usuário?',
    cfgDesativarMsg:        '{nome} perde o acesso ao Praxis até ser reativado.',
    cfgDesativar:           'Desativar',
    perfilDesc_supremo:     'Acesso total, inclusive a outros administradores e aos dados de demonstração.',
    perfilDesc_gestor:      'Gerencia usuários e cadastros, aprova e acompanha todos os pedidos.',
    perfilDesc_aprovador:   'Aprova ou reprova pedidos e consulta os relatórios.',
    perfilDesc_comprador:   'Registra cotações e conduz a compra até a entrega.',
    perfilDesc_financeiro:  'Cuida das parcelas e dos pagamentos, com acesso aos relatórios.',
    perfilDesc_solicitante: 'Abre pedidos e acompanha o andamento dos seus.',
    cfgEmpresasDesc:        'Cada pedido pertence a uma empresa do grupo.',
    cfgCategoriasDesc:      'Organizam pedidos e relatórios por tipo de gasto.',
    cfgFornecedoresDesc:    'Entram automaticamente quando uma cotação é registrada.',
    cfgBuscarFornecedor:    'Buscar por nome ou CNPJ',
    cfgSegmento:            'Segmento',
    cfgSegmentoPh:          'Ex.: Varejo, Serviços',
    cfgRazaoSocial:         'Razão social ou nome fantasia',
    cfgCnpjInvalido:        'O CNPJ precisa ter 14 dígitos.',
    cfgInativarEmpresaTitulo:'Inativar empresa?',
    cfgInativarEmpresaMsg:  '{nome} deixa de receber novos pedidos. Os pedidos existentes continuam visíveis.',
    cfgInativar:            'Inativar',
    cfgEmpresaAtivaDesc:    'Só empresas ativas recebem novos pedidos.',
    cfgCor:                 'Cor',
    cfgPrevia:              'Prévia',
    cfgNomeCategoriaPh:     'Ex.: Manutenção predial',
    cfgSemEmpresasTitulo:   'Nenhuma empresa',
    cfgSemEmpresasSub:      'Cadastre a primeira empresa para começar a receber pedidos.',
    cfgSemCategoriasTitulo: 'Nenhuma categoria',
    cfgSemCategoriasSub:    'Crie categorias para organizar os pedidos por tipo de gasto.',
    cfgSemFornecedoresTitulo:'Nenhum fornecedor ainda',
    cfgSemFornecedoresSub:  'Os fornecedores aparecem aqui quando a primeira cotação é registrada.',
    cfgGeralResumo:         'Seu acesso e as preferências deste navegador.',
    cfgPreferencias:        'Preferências',
    cfgAparencia:           'Aparência',
    cfgAparenciaDesc:       'Tema da interface neste navegador.',
    cfgTemaEscuro:          'Escuro',
    cfgTemaClaro:           'Claro',
    cfgSeuAcesso:           'Seu acesso',
    cfgResetMsg:            'Pedidos, cotações e histórico do ambiente demo serão apagados e recriados. Não é possível desfazer.',
    erroMarcarLidas:       'Não foi possível marcar as notificações como lidas.',
    erroMarcarLida:        'Não foi possível marcar a notificação como lida.',
    novaNotificacao:       'Nova notificação',
    erroAcessarDemo:       'Erro ao acessar modo demo. Tente novamente.',
    erroEnviarEmail:       'Erro ao enviar e-mail. Verifique o endereço.',
    erroSair:              'Erro ao sair. Tente novamente.',
    recuperarSenha:        'Recuperar senha',
    entrando:              'Entrando…',

    // Offline / errors
    semConexao:           'Sem conexão. Você pode consultar, mas salvar fica bloqueado até a internet voltar.',
    semConexaoAcao:       'Sem conexão. Tente de novo quando a internet voltar.',
    conexaoRestabelecida: 'Conexão restabelecida.',
    erroCarregar:         'Erro ao carregar. Verifique sua conexão.',
    semAcesso:            'Sem acesso',
    semAcessoMsg:         'Você não tem permissão para visualizar este pedido, ou ele não existe.',

    // Tour
    tourStep1Titulo:  'Quadro de pedidos',
    tourStep1Desc:    'Cada coluna é uma etapa da compra. Os pedidos andam da esquerda para a direita até o pagamento.',
    tourStep2Titulo:  'Novo pedido',
    tourStep2Desc:    'Descreva o que precisa comprar e envie. O pedido segue para cotação e aprovação.',
    tourStep3Titulo:  'Notificações',
    tourStep3Desc:    'Aprovações, cotações prontas, prazos e menções chegam aqui assim que acontecem.',
    tourStep4Titulo:  'Sua conta',
    tourStep4Desc:    'Seu perfil, a troca entre tema claro e escuro e a saída ficam neste menu.',
    tourStep5Titulo:  'Configurações',
    tourStep5Desc:    'Usuários, empresas, categorias e fornecedores. Visível só para gestores.',
    tourPular:        'Pular',
    tourProximo:      'Próximo',
    tourVoltar:       'Voltar',
    tourConcluir:     'Concluir',
    tourPasso:        'Passo',
    tourDe:           'de',

    // Topbar / nav
    navPedidos:             'Pedidos',
    navRelatorios:          'Relatórios',
    navConfiguracoes:       'Configurações',
    navAjustes:             'Ajustes',
    navBuscar:              'Buscar',
    navConta:               'Conta',
    navSair:                'Sair',
    navNavegacao:           'Navegação principal',
    tooltipPaleta:          'Buscar (Ctrl+K)',
    tooltipNotificacoes:    'Notificações',
    tooltipFecharConfig:    'Fechar configurações',
    tooltipSair:            'Sair da conta',
    tooltipConta:           'Sua conta',
    tooltipMenu:            'Menu',
    confirmarSair:          'Sair do Praxis?',
    confirmarSairMsg:       'Você volta para a tela de entrada. Pedidos e rascunhos salvos continuam onde estão.',
    menuTemaClaro:          'Usar tema claro',
    menuTemaEscuro:         'Usar tema escuro',
    menuAtalhos:            'Buscar e atalhos',
    menuPerfil:             'Perfil',
    semAcessoTela:          'Essa tela não está disponível para o seu perfil.',
    pagina404Titulo:        'Página não encontrada',
    pagina404Texto:         'O endereço {tela} não corresponde a nenhuma tela do Praxis.',
    pagina404Botao:         'Ir para pedidos',
    navMinhaFila:           'Minha fila',
    navCadastros:           'Cadastros',
    campoDataPlaceholder:   'dd/mm/aaaa',
    campoDataCalendario:    'Calendário',
    campoDataMesAnterior:   'Mês anterior',
    campoDataProximoMes:    'Próximo mês',
    campoDataLimpar:        'Limpar',
    campoDataHoje:          'Hoje',
    demoPreparando:         'Preparando a demonstração com as datas de hoje…',
    demoFaixaTitulo:        'Modo demonstração',
    demoFaixaDetalhe:       ': dados fictícios, restaurados todo dia. Crie, aprove e cancele à vontade.',
    demoFaixaRestaurar:     'Restaurar dados',
    demoFaixaSair:          'Sair da demo',

    // Notificações
    notifMarcarTodas:       'Marcar todas como lidas',
    notifNovaUma:           'nova',
    notifNovasVarias:       'novas',
    notifNaoLida:           'Não lida',
    notifVazioTitulo:       'Tudo em dia',
    notifVazioTexto:        'Aprovações, cotações e prazos dos seus pedidos aparecem aqui.',

    // Pluralizáveis
    selecionado:      'selecionado',
    selecionados:     'selecionados',
    pedidoExportado:  'pedido exportado',
    pedidosExportados:'pedidos exportados',
    pedidoCancelado:  'pedido cancelado',
    pedidosCancelados:'pedidos cancelados',

    // Erros / feedback
    confirmarCancelamento: 'Confirmar cancelamento',
    motivoLabel:           'Motivo',
    motivoPlaceholder:     'Selecionar motivo…',
    motivoOutros:          'Descreva o motivo',
    erroCarregarPedidos:   'Não foi possível carregar os pedidos',
    verificarConexao:      'Verifique sua conexão e recarregue a página.',
    erroCamposObrigatorios:'Preencha todos os campos obrigatórios.',
    bulkNenhumCancelavel:  'Nenhum pedido selecionado pode ser cancelado com seu perfil.',
    selecionarMotivo:      'Selecione o motivo de cancelamento.',
    descreverMotivo:       'Descreva o motivo.',
    erroCancelarPedidos:   'Erro ao cancelar pedidos: ',
    seraoCancelados:       'serão cancelados',

    // Tela de pedidos — passada de acabamento
    filtros:               'Filtros',
    npUrgenteDesc:         'Destaca o pedido no quadro e avisa quem precisa agir.',
    campoObrigatorio:      'Obrigatório',
    quantidadeMinima:      'Informe pelo menos 1',
    dataNoPassado:         'A data não pode estar no passado',
    escolhaCategoria:      'Escolha uma categoria',
    pedidoAberto:          'Pedido aberto.',
    erroAbrirPedido:       'Não foi possível abrir o pedido. Tente novamente.',
    recarregar:            'Recarregar',
    pedidoSing:            'pedido',
    pedidosPlural:         'pedidos',
    urgenteSing:           'urgente',
    urgentesPlural:        'urgentes',
    emAberto:              'em aberto',
    verMais:               'Mostrar mais',
    verMenos:              'Mostrar menos',
    colunasAnteriores:     'Colunas anteriores',
    proximasColunas:       'Próximas colunas',
    comentarioNaoLido:     'Comentário não lido',
    urgenteTag:            'Urgente',
    nenhumResultadoPara:   'Nada encontrado para',
    semPendentesTitulo:    'Nada pendente com você',
    semPendentesSub:       'Quando um pedido precisar da sua ação, ele aparece aqui.',
    verTodos:              'Ver todos os pedidos',
    semPedidosFiltro:      'Nenhum pedido neste filtro',
    semPedidosFiltroSub:   'Escolha outro filtro ou veja todos os pedidos.',
    ordemRecentes:         'Mais recentes',
    ordemAntigos:          'Mais antigos',
    ordemMaiorValor:       'Maior valor',
    ordemMenorValor:       'Menor valor',
    ordemTitulo:           'Título (A–Z)',
    ordemStatus:           'Etapa do fluxo',
    ordenarPor:            'Ordenar por',
    paginaDe:              'de',
    selecionarPagina:      'Selecionar todos desta página',
    colValor:              'Valor',
    colCriadoEm:           'Criado em',
    inativa:               'inativa',
    duplicarBase:          'Cópia de',
    duplicarAjuste:        'revise os dados e defina o novo prazo',
    btnCriarCopia:         'Criar cópia',
    visaoQuadro:           'Quadro',
    visaoLista:            'Lista',
    visoes:                'Visões',
    visaoInclui:           'Esta visão guarda',
    renomear:              'Renomear',
    remover:               'Remover',
    informeNomeVisao:      'Dê um nome para a visão',
    visaoSalva:            'Visão salva.',
    visaoRemoverMsg:       'Seus pedidos não são afetados.',
    bulkSeraCancelado:     'pedido será cancelado.',
    bulkSeraoCancelados:   'pedidos serão cancelados.',
    bulkDemaisFicam:       'Os outros {n} já passaram da etapa em que o cancelamento é permitido e ficam como estão.',
    outros:                'outros',
    semPedidosSub:         'Quando um pedido for aberto, ele aparece aqui com o andamento de cada etapa.',

    // Tela de pedidos — redesenho da Inscrição
    filtrosRapidos:        'Filtros rápidos',
    visualizacao:          'Visualização',
    resumoEtapas:          'Cada número abaixo é uma etapa do caminho.',
    resumoEncerrados:      'Reprovados e cancelados ficam aqui para consulta.',
    resumoNenhum:          'Nenhum pedido',
    filaDescGestor:        'Entram aqui os pedidos em aberto que são urgentes ou estão parados há mais de dois dias.',
    filaDescAprovador:     'Entram aqui os pedidos que esperam a sua aprovação.',
    filaDescComprador:     'Entram aqui os pedidos ainda sem comprador e as cotações que você assumiu.',
    filaDescFinanceiro:    'Entram aqui os pedidos entregues que esperam pagamento.',
    filaDescSolicitante:   'Entram aqui os seus pedidos que ainda estão em andamento.',
    etapas:                'Etapas',
    etapaDaFila:           'Etapa com mais pedidos na sua fila',
    etapaCurtaSolicitado:  'Solicit.',
    etapaCurtaCotacao:     'Cotação',
    etapaCurtaAprovacao:   'Aprovação',
    etapaCurtaAprovado:    'Aprovado',
    etapaCurtaComprado:    'Comprado',
    etapaCurtaEntregue:    'Entregue',
    etapaCurtaPago:        'Pago',
    etapaCurtaReprovado:   'Reprovado',
    etapaCurtaCancelado:   'Cancelado',
    semValor:              'Sem valor',
    prazoSem:              'Sem prazo',
    prazoVenceHoje:        'Vence hoje',
    prazoFalta1:           'Falta 1 dia',
    prazoFaltam:           'Faltam {n} dias',
    prazoAtrasado1:        'Atrasado 1 dia',
    prazoAtrasado:         'Atrasado {n} dias',
    prazoEntregueHoje:     'Entregue hoje',
    prazoEntregue1:        'Entregue há 1 dia',
    prazoEntregue:         'Entregue há {n} dias',
    prazoPagoEm:           'Pago em {d}',
    prazoReprovadoEm:      'Reprovado em {d}',
    prazoCanceladoEm:      'Cancelado em {d}',
    filtrosAtivos1:        '1 ativo',
    filtrosAtivos:         '{n} ativos',
    verResultado0:         'Nenhum pedido',
    verResultado1:         'Ver 1 pedido',
    verResultado:          'Ver {n} pedidos',
    periodoCriacao:        'Criados entre',
    periodoE:              'e',
    dataInicial:           'Data inicial',
    dataFinal:             'Data final',
    colComprador:          'Comprador',
    colEtapa:              'Etapa',
    colPrazo:              'Prazo',
    ordemPrazo:            'Prazo mais próximo',
    visoesSalvas:          'Visões salvas',
    salvarVisaoAtual:      'Salvar esta combinação',
    visoesVazio:           'Guarde a combinação de filtros atual para voltar a ela com um toque.',
    carregandoPedidos:     'Carregando pedidos',
    paginacao:             'Paginação',
  },

  en: {
    // Login / auth
    titulo:           'Orders',
    relatorios:       'Reports',
    configuracoes:    'Settings',
    btnEntrar:        'Sign in',
    btnDemo:          'Open demo mode',
    tagline:          'Corporate procurement management',
    emailLabel:       'Email',
    senhaLabel:       'Password',
    esqueci:          'Forgot password',
    escolherIdioma:   'Choose demo language',
    continuar:        'Continue',
    voltar:           'Back',
    novoPedido:       'New order',
    todos:            'All',
    urgentes:         'Urgent',
    meusPedidos:      'My orders',
    estaSemana:       'This week',
    encerrados:       'Closed',
    resetEnviado:     'Check your email',
    resetMsg:         'Check your inbox and follow the instructions to reset your password.',
    emailReset:       'Enter your account email. We will send you a link to create a new password.',
    enviarLink:       'Send link',
    loginTitulo:      'Every purchase has a path.',
    loginTitulo2:     'From request to payment.',
    loginTexto:       'Who requests, who quotes, who approves and who pays. Seven steps, each with an owner, a deadline and a history.',
    loginCardTitulo:  'Sign in to your account',
    loginCardSub:     'Use the email registered by your company.',
    demoDica:         'Sample data, no sign-up.',
    mostrarSenha:     'Show password',
    ocultarSenha:     'Hide password',
    alternarTema:     'Toggle light and dark theme',
    voltarLogin:      'Back to sign in',
    resetMsgPara:     'If there is an account for {email}, you will receive a link to create a new password. Check your spam folder too.',
    preenchaCampos:   'Enter your email and password.',
    informeEmail:     'Enter your email.',
    loginEtapas:      'Request|Quote|Approval|Approved|Purchase|Delivery|Payment',

    // Shared UI
    fechar:           'Close',
    cancelar:         'Cancel',
    salvar:           'Save',
    confirmar:        'Confirm',
    editar:           'Edit',
    excluir:          'Delete',
    selecionar:       'Select…',
    opcional:         'Optional',
    limpar:           'Clear',

    // Topbar tooltips
    tooltipTema:      'Toggle theme',
    tooltipNotif:     'Notifications',
    tooltipConfig:    'Settings',
    tooltipCmd:       'Command palette (Ctrl+K)',

    // Pedidos toolbar / pills
    meusPendentes:    'My pending',
    buscarPedido:     'Search order…',
    salvarVisao:      'Save view',
    periodo:          'Period:',

    // List filters & columns
    todasEmpresas:    'All companies',
    todasCategorias:  'All categories',
    TodosCompradores: 'All buyers',
    limparFiltros:    'Clear filters',
    colPedido:        'Order',
    colEmpresa:       'Company',
    colSolicitante:   'Requester',
    colValorEst:      'Est. value',
    colData:          'Date',
    paginaAnt:        'Previous',
    paginaProx:       'Next',

    // Kanban empty states
    semPedidosColuna: 'No orders here',
    nenhumResultado:  'No results found',
    nenhumPedido:     'No orders here yet',
    ajustarFiltro:    'Try adjusting the filter or search term.',
    abrirPrimeiro:    'Create your first order by clicking "New order".',

    // New order modal
    npTitulo:           'Title',
    npTituloPlaceholder:'E.g. Box of disposable gloves',
    npEmpresa:          'Company',
    npQuantidade:       'Quantity',
    npUnidade:          'Unit',
    npData:             'Needed by',
    npValor:            'Estimated value',
    npCC:               'Cost center',
    npCategoria:        'Category',
    npUrgente:          'Urgent order',
    npObs:              'Notes',
    npObsPlaceholder:   'Describe relevant details for the purchase…',
    btnAbrirPedido:     'Open order',
    duplicarPedido:     'Duplicate order',

    // Saved views
    nomeVisao:          'View name',
    nomeVisaoPlaceholder:'E.g. Urgent this week',

    // Bulk actions
    exportarCSV:          'Export CSV',
    cancelarSelecionados: 'Cancel selected',
    desmarcarTudo:        'Deselect all',

    // Order detail — action buttons
    btnExportarPDF:       'Export PDF',
    btnDuplicar:          'Duplicate',
    btnReabrir:           'Reopen order',
    btnCancelarPedido:    'Cancel order',
    btnAssumirPedido:     'Claim order',
    btnLiberarPedido:     'Release order',
    btnAprovar:           'Approve',
    btnReprovar:          'Reject',
    btnExecutarCompra:    'Record purchase',
    btnConfirmarEntrega:  'Confirm delivery',
    btnConfirmarPagamento:'Confirm payment',
    btnEditarPedido:      'Edit order',

    // Order detail — sections & UI
    secaoAnexos:          'Attachments',
    secaoAtividade:       'Activity',
    secaoCotacoes:        'Quotes',
    secaoParcelas:        'Installments',
    btnAdicionarAnexo:    'Add',
    btnComparar:          'Compare',
    btnNovaCotacao:       'New quote',
    btnAdicionarParcela:  'Add installment',
    btnEnviarComentario:  'Send',
    placeholderComentario:'Comment… use @ to mention',

    // Order detail — meta labels & people
    metaEmpresa:          'Company',
    metaQtd:              'Quantity',
    metaCategoria:        'Category',
    metaNecessario:       'Needed by',
    metaValorEst:         'Estimated value',
    metaCentro:           'Cost center',
    metaValorFinal:       'Final value',
    metaDataCompra:       'Purchase date',
    metaDataEntrega:      'Delivery date',
    pessoasEnvolvidas:    'People involved',
    solicitanteLabel:     'Requester',
    criouPedido:          'Created the order',
    compradorLabel:       'Buyer',
    semCotacoes:          'No quotes',
    aguardandoComprador:  'Waiting for buyer',
    aprovadoresLabel:     'Approvers',
    aprovadoStatus:       'Approved',
    aguardandoStatus:     'Waiting',
    urgente:              'Urgent',
    economiaLabel:        'Savings',
    reabertoDe:           'Reopened from',
    reabertoComo:         'Reopened as',

    // Order detail — modal labels
    confirmarCompra:           'Confirm purchase',
    fornecedorLabel:           'Supplier',
    valorFinalLabel:           'Final value',
    condicaoPagLabel:          'Payment terms',
    dataCompraLabel:           'Purchase date',
    numParcelasLabel:          'Number of installments',
    vencimentoPrimeiraLabel:   '1st installment due date',
    selecionar:                'Select…',
    especifique:               'Specify',
    especifiquePlaceholder:    'Describe the reason…',
    justReaberturaLabel:       'Reopening justification',
    justReaberturaPlaceholder: 'Explain what changed or why you are reopening this order…',
    reabrirDescricao:          'A new order will be created as Requested with this order\'s data, linked to the original. This order remains as Rejected.',
    btnCancelar:               'Cancel',
    tituloReprovar:            'Reject order',
    tituloCancelar:            'Cancel order',
    tituloReabrir:             'Reopen order',

    // Toast / feedback messages — order detail
    pedidoNaoEncontrado:       'Order not found',
    pedidoRemovidoMsg:         'The order you tried to access does not exist or was removed.',
    semAcessoPedido:           'You do not have permission to access this order.',
    erroCarregarPedido:        'Failed to load order.',
    pedidoJaAssumido:          'Order was already claimed by another buyer.',
    pedidoAssumido:            'Order claimed. You are the responsible buyer.',
    erroAssumir:               'Failed to claim order.',
    pedidoLiberado:            'Order released to queue.',
    erroLiberarPedido:         'Failed to release order.',
    pedidoJaProcessado:        'This order was already processed by another approver.',
    pedidoAprovado:            'Order approved.',
    erroAprovar:               'Failed to approve.',
    selecionarMotivoSimples:   'Select a reason.',
    pedidoReprovado:           'Order rejected.',
    erroReprovar:              'Failed to reject.',
    compraRegistrada:          'Purchase recorded.',
    erroRegistrarCompra:       'Failed to register purchase.',
    entregaConfirmada:         'Delivery confirmed.',
    erroConfirmarEntrega:      'Failed to confirm delivery.',
    pagamentoConfirmado:       'Payment confirmed. Order completed.',
    erroConfirmarPagamento:    'Failed to confirm payment.',
    pedidoCanceladoMsg:        'Order cancelled.',
    erroCancelarPedido:        'Failed to cancel order.',
    pedidoAtualizado:          'Order updated.',
    erroSalvarAlteracoes:      'Failed to save changes.',
    erroEnviarComentario:      'Failed to send comment.',
    cotacaoIndicada:           'Quote selected. The order moved to approval.',
    erroIndicarCotacao:        'Failed to select quote.',
    pagamentoRegistrado:       'Payment recorded.',
    erroRegistrarPagamento:    'Failed to register payment.',
    comprovanteAnexado:        'Receipt attached.',
    erroAnexarComprovante:     'Failed to attach receipt.',
    fornecedorValorObrig:      'Supplier and value are required.',
    cotacaoAdicionada:         'Quote recorded.',
    erroSalvarCotacao:         'Failed to save quote.',
    pdfExportado:              'PDF exported.',
    erroExportarPDF:           'Failed to export PDF. Check your connection.',
    informarJustificativa:     'Provide the reopening justification.',
    pedidoReabertoComo:        'Order reopened as',
    tipoNaoPermitido:          'File type not allowed. Use PDF, image (JPG/PNG/WebP), DOCX, or XLSX.',
    arquivoMuitoGrande:        'exceeds the 10 MB limit.',
    erroEnviarAnexo:           'Failed to upload: ',
    anexoRemovido:             'Attachment removed.',
    erroRemoverAnexo:          'Failed to remove: ',

    // Order detail — redesign (decision panel, path ruler, sections)
    dtFechar:                  'Close',
    dtMaisAcoes:               'More actions',
    dtDadosPedido:             'Order details',
    dtDescricao:               'Description',
    dtComparadasIndicada:      'Difference to the selected one',
    dtComparadasMenor:         'Difference to the lowest',
    dtLadoALadoTitulo:         'Quotes side by side',
    dtLadoALado:               'Side by side',
    dtComentario:              'Comment',
    dtComentarioPlaceholder:   'Write a comment',
    dtMenciona:                'mentions',
    dtEnvia:                   'sends',
    dtComentar:                'Comment',
    dtAnexar:                  'Attach',
    dtReprovarIntro:           'The order goes back to the requester with the reason given. They can reopen it with changes.',
    dtCancelarIntro:           'The order leaves the flow and is recorded as cancelled. This cannot be undone.',
    dtVoltar:                  'Back',
    dtPropostaIndicada:        'Selected quote',
    dtCotacaoIndicada:         'Selected quote',
    dtNomeFornecedor:          'Supplier name',
    dtRegistrarCotacao:        'Record quote',
    dtRegistrarPagamento:      'Record payment',
    dtDuplicarPedido:          'Duplicate order',
    dtProximoPasso:            'Next step',
    dtComVoce:                 'With you',
    dtAcoesDoPasso:            'Actions for this step',
    dtResponsavel:             'Responsible',
    dtPrazo:                   'Due date',
    dtSemResponsavel:          'No buyer yet',
    dtCompradorDesignado:      'Assigned buyer',
    dtAprovadoresEmpresa:      'Company approvers',
    dtEquipeFinanceira:        'Finance team',
    dtRecebimento:             'Receiving',
    dtSolicTituloPode:         'Claim the order to start quoting',
    dtSolicTitulo:             'Waiting for a buyer',
    dtSolicTextoPode:          'Whoever claims it gathers the quotes and selects the best one.',
    dtSolicTexto:              'Quoting starts as soon as a buyer claims the order.',
    dtCotTituloVazio:          'Record the quotes',
    dtCotTituloAndamento:      'Quoting in progress',
    dtCotTituloIndicar:        'Select the best quote',
    dtCotTextoOutros:          'The buyer is gathering supplier quotes.',
    dtCotTextoVazio:           'Gather at least three quotes and select the best one to send for approval.',
    dtCotTextoPoucas:          'Record more quotes or select the best one in the list to send for approval.',
    dtCotTextoIndicar:         'Selecting a quote in the list sends the order for approval.',
    dtMenorValor:              'Lowest',
    dtAprovTituloPode:         'Waiting for your decision',
    dtAprovTitulo:             'Under review by the approver',
    dtFoiIndicada:             'was the selected quote',
    dtEntre:                   'among',
    dtCotacoesMin:             'quotes',
    dtAprovSemIndicada:        'The order is with the approver.',
    dtFrenteEstimado:          'Versus estimate',
    dtFrenteMaisCara:          'versus the highest quote',
    dtAprovadoTituloPode:      'Record the purchase',
    dtAprovadoTitulo:          'Approved, waiting for the purchase',
    dtAprovadoTextoPode:       'Enter the supplier, final amount and installments.',
    dtAprovadoTexto:           'The buyer records the purchase with the supplier.',
    dtValorAprovado:           'Approved amount',
    dtCompradoTituloPode:      'Confirm delivery when it arrives',
    dtCompradoTitulo:          'Waiting for delivery',
    dtCompradoTexto:           'Check the item and confirm receipt. Finance then follows the payment.',
    dtEntregueTitulo:          'Delivered, waiting for payment',
    dtEntregueTituloConcluir:  'Complete the payment',
    dtSemParcelas:             'No installments recorded.',
    dtPago:                    'Paid',
    dtParcela:                 'Installment',
    dtConcluido:               'Completed',
    dtPagoTitulo:              'Order completed',
    dtValorPago:               'Amount paid',
    dtConcluidoEm:             'Completed on',
    dtDoPedidoAoPagamento:     'From request to payment',
    dtReprovado:               'Rejected',
    dtReprovadoTitulo:         'Order rejected',
    dtJaReaberto:              'Already reopened as',
    dtDicaReabrir:             'To try again with changes, use Reopen order in the actions menu.',
    dtCancelado:               'Cancelled',
    dtCanceladoTitulo:         'Order cancelled',
    dtCanceladoTexto:          'The order left the purchasing flow.',
    dtCotVazioTitulo:          'No quotes yet',
    dtCotVazioPode:            'Record at least three quotes to compare and send for approval.',
    dtCotVazioSolic:           'Quotes show up here after a buyer claims the order.',
    dtCotVazioOutros:          'No quote was recorded for this order.',
    dtIndicada:                'Selected',
    dtBaseComparacao:          'Base',
    dtMaisBarataQueIndicada:   'Cheaper than the selected quote',
    dtAbrirArquivo:            'Open file',
    dtAbrirArquivoCotacao:     'Open quote file',
    dtIndicar:                 'Select',
    dtIndicarTitulo:           'Select this quote and send the order for approval',
    dtIndicarConfirmaTitulo:   'Select and send for approval?',
    dtIndicarConfirmaTexto:    'The order goes to the approver with this quote.',
    dtIndicarConfirmaOk:       'Select and send',
    dtSemCondicoes:            'No terms given',
    dtEconomiaFrase1:          'The selected quote is',
    dtEconomiaFrase2:          'below the highest quote.',
    dtAtividadeVazia:          'No activity yet',
    dtAtividadeVaziaTexto:     'Stage changes, comments and attachments show up here.',
    dtPagosDe:                 'paid of',
    dtPercentualPago:          'Percentage paid',
    dtPagar:                   'Pay',
    dtVerComprovante:          'View receipt',
    dtAnexarComprovante:       'Attach receipt',
    dtAnexosVazio:             'No attachments',
    dtAnexosVazioTexto:        'Specs, reference photos and supporting documents go here.',
    dtTempoPorEtapa:           'Time per stage',
    dtAteAgora:                'so far',
    dtAgora:                   'now',

    // Dashboard
    dashTotalGasto:       'Total spent in period',
    dashTotalPedidos:     'Total orders',
    dashAgAprovacao:      'Pending approval',
    dashAVencer:          'Installments due (7 days)',
    dashEconomia:         'Accumulated savings',
    dashEconomiaVs:       'Quotes vs. best price',
    dashExportar:         'Export',
    dashExportarExcel:    'Export Excel',
    dashExportarPDF:      'Export PDF',
    dashGastoPorEmpresa:  'Spend by company',
    dashProxParcelas:     'Upcoming installments',
    dashStatus:           'Order status',
    dashGastoPorCategoria:'Spend by category',
    dashGastoMensal:      'Monthly spend — last 6 months',
    dashEvolucaoGastos:   'Spending over time',
    dashPeriodo:          'Period',
    dashVisao:            'Financial and operational overview',
    semDados:             'No data for this period.',
    semUrgentes:          'No urgent orders',
    nenhumaParcela:       'No upcoming installments.',
    dashHoje:             'Today',
    periodoMes:           'This month',
    periodoTri:           'This quarter',
    periodoAno:           'This year',
    periodoLivre:         'Selected period',
    filtroPilulaMes:      'Month',
    filtroPilulaTri:      'Quarter',
    filtroPilulaAno:      'Year',
    filtroPilulaLivre:    'Custom',
    filtroPilulaAte:      'to',
    noPeriodo:            'In period',
    parcela:              'installment',
    parcelas:             'installments',
    parcelaNum:           'Installment',

    // Config
    configUsuarios:       'Users',
    btnNovoUsuario:       'New user',
    btnNovaEmpresa:       'New company',
    btnNovaCategoria:     'New category',
    secaoEmpresas:        'Companies',
    secaoCategorias:      'Categories',
    secaoFornecedores:    'Suppliers',
    editarLabel:          'Edit',
    salvarLabel:          'Save',
    novoUsuarioTitulo:    'New user',
    editarUsuarioTitulo:  'Edit user',
    novaEmpresaTitulo:    'New company',
    editarEmpresaTitulo:  'Edit company',
    novaCategoriaTitulo:  'New category',
    editarCategoriaTitulo:'Edit category',
    editarFornTitulo:     'Edit supplier',
    nomeObrigatorio:      'Name is required.',
    emailObrigatorio:     'Email is required.',
    emailInvalido:        'Invalid email format.',
    perfilObrigatorio:    'Select a profile.',
    empresaObrigatoria:   'Link at least one company.',
    modoDemo:             'Changes are not saved in demo mode.',
    usuarioAtualizado:    'User updated.',
    usuarioCriado:        'User created. Set the sign-in password in Firebase Authentication.',
    empresaAtualizada:    'Company updated.',
    empresaCriada:        'Company created.',
    categoriaAtualizada:  'Category updated.',
    categoriaCriada:      'Category created.',
    fornecedorAtualizado: 'Supplier updated.',
    erroSalvar:           'Failed to save.',
    cnpjNaoInformado:      'CNPJ not provided',
    categoriaPadraoLabel:  'Default',
    catPersonalizadaLabel: 'Custom',
    usosPedido:            'order',
    usosPedidos:           'orders',
    erroExcluir:          'Failed to delete.',
    btnResetarDemo:        'Reset data',
    demoResetadoMsg:       'Sample data reset.',
    demoErroReset:         'Could not reset the sample data.',
    confirmarResetDemo:    'Reset sample data?',
    tourTitulo:            'Guided tour',
    tourDesc:              'Review the welcome tour that introduces the main features of the system.',
    btnVerTour:            'Start tour',
    // Settings (polish pass)
    cfgAtivos:              'Active',
    cfgInativos:            'Inactive',
    cfgAtivo:               'Active',
    cfgInativo:             'Inactive',
    cfgAtiva:               'Active',
    cfgInativa:             'Inactive',
    cfgFiltrarStatus:       'Filter by status',
    cfgBuscarUsuario:       'Search by name or email',
    cfgColUsuario:          'User',
    cfgColPerfil:           'Role',
    cfgColEmpresas:         'Companies',
    cfgColUltimoAcesso:     'Last access',
    cfgColStatus:           'Status',
    cfgColAcoes:            'Actions',
    cfgColCategoria:        'Category',
    cfgColTipo:             'Type',
    cfgColPedidos:          'Orders',
    cfgColFornecedor:       'Supplier',
    cfgColValor:            'Value',
    cfgTodasEmpresasTxt:    'All companies',
    cfgNenhuma:             'None',
    cfgSemAcessoDica:       'No sign-in recorded yet',
    cfgNunca:               'Never',
    cfgAgora:               'Now',
    cfgHoje:                'Today',
    cfgOntem:               'Yesterday',
    cfgVoce:                'You',
    cfgNovoCurto:           'New',
    cfgNovaCurto:           'New',
    cfgUsuarioSing:         'user',
    cfgUsuarioPlur:         'users',
    cfgInativoSing:         'inactive',
    cfgInativoPlur:         'inactive',
    cfgTodosAtivos:         'all active',
    cfgUsuariosDesc:        'The role defines what each person can do.',
    cfgInativaSing:         'inactive',
    cfgInativaPlur:         'inactive',
    cfgCriadaEquipeSing:    'created by the team',
    cfgCriadaEquipePlur:    'created by the team',
    cfgNadaEmAberto:        'Nothing open',
    cfgEmpresaSing:         'company',
    cfgEmpresaPlur:         'companies',
    cfgCategoriaSing:       'category',
    cfgCategoriaPlur:       'categories',
    cfgFornecedorSing:      'supplier',
    cfgFornecedorPlur:      'suppliers',
    cfgSemResultadoTitulo:  'No results',
    cfgSemResultadoBusca:   'Nothing matches “{q}”. Check the spelling or try another term.',
    cfgSemInativosTitulo:   'No inactive users',
    cfgSemInativosSub:      'Deactivated users show up here and can be reactivated when needed.',
    cfgSemUsuariosTitulo:   'No users',
    cfgSemUsuariosSub:      'Add your team to start creating orders.',
    cfgLimparBusca:         'Clear search',
    cfgVerTodos:            'Show all',
    cfgEditarX:             'Edit {nome}',
    cfgNome:                'Name',
    cfgEmail:               'Email',
    cfgNomeCompleto:        'Full name',
    cfgEmailFixo:           'The email is the sign-in and cannot be changed.',
    cfgAcesso:              'Access',
    cfgSelecionarTodas:     'Select all',
    cfgLimparSelecao:       'Clear',
    cfgSomenteSupremo:      'Only a Supreme user can change another Supreme user.',
    cfgNaoDesativarVoce:    'You cannot deactivate your own access.',
    cfgDesativarTitulo:     'Deactivate user?',
    cfgDesativarMsg:        '{nome} loses access to Praxis until reactivated.',
    cfgDesativar:           'Deactivate',
    perfilDesc_supremo:     'Full access, including other admins and the demo data.',
    perfilDesc_gestor:      'Manages users and records, approves and tracks every order.',
    perfilDesc_aprovador:   'Approves or rejects orders and views reports.',
    perfilDesc_comprador:   'Records quotes and runs the purchase through delivery.',
    perfilDesc_financeiro:  'Handles installments and payments, with access to reports.',
    perfilDesc_solicitante: 'Creates orders and follows their progress.',
    cfgEmpresasDesc:        'Every order belongs to one company in the group.',
    cfgCategoriasDesc:      'Group orders and reports by type of spend.',
    cfgFornecedoresDesc:    'Added automatically when a quote is recorded.',
    cfgBuscarFornecedor:    'Search by name or CNPJ',
    cfgSegmento:            'Segment',
    cfgSegmentoPh:          'e.g. Retail, Services',
    cfgRazaoSocial:         'Legal or trade name',
    cfgCnpjInvalido:        'The CNPJ must have 14 digits.',
    cfgInativarEmpresaTitulo:'Deactivate company?',
    cfgInativarEmpresaMsg:  '{nome} stops receiving new orders. Existing orders stay visible.',
    cfgInativar:            'Deactivate',
    cfgEmpresaAtivaDesc:    'Only active companies receive new orders.',
    cfgCor:                 'Color',
    cfgPrevia:              'Preview',
    cfgNomeCategoriaPh:     'e.g. Building maintenance',
    cfgSemEmpresasTitulo:   'No companies',
    cfgSemEmpresasSub:      'Add the first company to start receiving orders.',
    cfgSemCategoriasTitulo: 'No categories',
    cfgSemCategoriasSub:    'Create categories to group orders by type of spend.',
    cfgSemFornecedoresTitulo:'No suppliers yet',
    cfgSemFornecedoresSub:  'Suppliers show up here once the first quote is recorded.',
    cfgGeralResumo:         'Your access and the preferences for this browser.',
    cfgPreferencias:        'Preferences',
    cfgAparencia:           'Appearance',
    cfgAparenciaDesc:       'Interface theme on this browser.',
    cfgTemaEscuro:          'Dark',
    cfgTemaClaro:           'Light',
    cfgSeuAcesso:           'Your access',
    cfgResetMsg:            'Orders, quotes and history in the demo environment will be deleted and recreated. This cannot be undone.',
    erroMarcarLidas:       'Could not mark notifications as read.',
    erroMarcarLida:        'Could not mark notification as read.',
    novaNotificacao:       'New notification',
    erroAcessarDemo:       'Failed to access demo mode. Please try again.',
    erroEnviarEmail:       'Failed to send email. Check the address.',
    erroSair:              'Failed to sign out. Please try again.',
    recuperarSenha:        'Reset password',
    entrando:              'Signing in…',

    // Offline / errors
    semConexao:           'You are offline. You can browse, but saving is blocked until the connection is back.',
    semConexaoAcao:       'You are offline. Try again when the connection is back.',
    conexaoRestabelecida: 'Connection restored.',
    erroCarregar:         'Failed to load. Check your connection.',
    semAcesso:            'No access',
    semAcessoMsg:         'You do not have permission to view this order, or it does not exist.',

    // Tour
    tourStep1Titulo:  'Order board',
    tourStep1Desc:    'Each column is a purchasing stage. Orders move from left to right until payment.',
    tourStep2Titulo:  'New order',
    tourStep2Desc:    'Describe what you need to buy and submit. The order moves on to quoting and approval.',
    tourStep3Titulo:  'Notifications',
    tourStep3Desc:    'Approvals, ready quotes, due dates and mentions show up here as they happen.',
    tourStep4Titulo:  'Your account',
    tourStep4Desc:    'Your profile, the light and dark theme switch and sign out live in this menu.',
    tourStep5Titulo:  'Settings',
    tourStep5Desc:    'Users, companies, categories and suppliers. Visible to managers only.',
    tourPular:        'Skip',
    tourProximo:      'Next',
    tourVoltar:       'Back',
    tourConcluir:     'Done',
    tourPasso:        'Step',
    tourDe:           'of',

    // Topbar / nav
    navPedidos:             'Orders',
    navRelatorios:          'Reports',
    navConfiguracoes:       'Settings',
    navAjustes:             'Settings',
    navBuscar:              'Search',
    navConta:               'Account',
    navSair:                'Sign out',
    navNavegacao:           'Main navigation',
    tooltipPaleta:          'Search (Ctrl+K)',
    tooltipNotificacoes:    'Notifications',
    tooltipFecharConfig:    'Close settings',
    tooltipSair:            'Sign out',
    tooltipConta:           'Your account',
    tooltipMenu:            'Menu',
    confirmarSair:          'Sign out of Praxis?',
    confirmarSairMsg:       'You will return to the sign-in screen. Saved orders and drafts stay where they are.',
    menuTemaClaro:          'Use light theme',
    menuTemaEscuro:         'Use dark theme',
    menuAtalhos:            'Search and shortcuts',
    menuPerfil:             'Role',
    semAcessoTela:          'That screen is not available for your role.',
    pagina404Titulo:        'Page not found',
    pagina404Texto:         'The address {tela} does not match any Praxis screen.',
    pagina404Botao:         'Go to orders',
    navMinhaFila:           'My queue',
    navCadastros:           'Records',
    campoDataPlaceholder:   'dd/mm/yyyy',
    campoDataCalendario:    'Calendar',
    campoDataMesAnterior:   'Previous month',
    campoDataProximoMes:    'Next month',
    campoDataLimpar:        'Clear',
    campoDataHoje:          'Today',
    demoPreparando:         'Preparing the demo with today’s dates…',
    demoFaixaTitulo:        'Demo mode',
    demoFaixaDetalhe:       ': sample data, restored every day. Create, approve and cancel freely.',
    demoFaixaRestaurar:     'Restore data',
    demoFaixaSair:          'Exit demo',

    // Notifications
    notifMarcarTodas:       'Mark all as read',
    notifNovaUma:           'new',
    notifNovasVarias:       'new',
    notifNaoLida:           'Unread',
    notifVazioTitulo:       'All caught up',
    notifVazioTexto:        'Approvals, quotes and due dates for your orders show up here.',

    // Pluralizáveis
    selecionado:      'selected',
    selecionados:     'selected',
    pedidoExportado:  'order exported',
    pedidosExportados:'orders exported',
    pedidoCancelado:  'order cancelled',
    pedidosCancelados:'orders cancelled',

    // Erros / feedback
    confirmarCancelamento: 'Confirm cancellation',
    motivoLabel:           'Reason',
    motivoPlaceholder:     'Select reason…',
    motivoOutros:          'Describe the reason',
    erroCarregarPedidos:   'Could not load orders',
    verificarConexao:      'Check your connection and reload the page.',
    erroCamposObrigatorios:'Please fill in all required fields.',
    bulkNenhumCancelavel:  'No selected order can be cancelled with your profile.',
    selecionarMotivo:      'Select a cancellation reason.',
    descreverMotivo:       'Describe the reason.',
    erroCancelarPedidos:   'Error cancelling orders: ',
    seraoCancelados:       'will be cancelled',

    // Orders screen — polish pass
    filtros:               'Filters',
    npUrgenteDesc:         'Highlights the order on the board and alerts whoever needs to act.',
    campoObrigatorio:      'Required',
    quantidadeMinima:      'Enter at least 1',
    dataNoPassado:         'The date cannot be in the past',
    escolhaCategoria:      'Choose a category',
    pedidoAberto:          'Order created.',
    erroAbrirPedido:       'Could not create the order. Please try again.',
    recarregar:            'Reload',
    pedidoSing:            'order',
    pedidosPlural:         'orders',
    urgenteSing:           'urgent',
    urgentesPlural:        'urgent',
    emAberto:              'open',
    verMais:               'Show more',
    verMenos:              'Show less',
    colunasAnteriores:     'Previous columns',
    proximasColunas:       'Next columns',
    comentarioNaoLido:     'Unread comment',
    urgenteTag:            'Urgent',
    nenhumResultadoPara:   'Nothing found for',
    semPendentesTitulo:    'Nothing waiting on you',
    semPendentesSub:       'When an order needs your action, it shows up here.',
    verTodos:              'See all orders',
    semPedidosFiltro:      'No orders in this filter',
    semPedidosFiltroSub:   'Pick another filter or see all orders.',
    ordemRecentes:         'Newest first',
    ordemAntigos:          'Oldest first',
    ordemMaiorValor:       'Highest amount',
    ordemMenorValor:       'Lowest amount',
    ordemTitulo:           'Title (A–Z)',
    ordemStatus:           'Workflow stage',
    ordenarPor:            'Sort by',
    paginaDe:              'of',
    selecionarPagina:      'Select all on this page',
    colValor:              'Amount',
    colCriadoEm:           'Created',
    inativa:               'inactive',
    duplicarBase:          'Copy of',
    duplicarAjuste:        'review the details and set a new deadline',
    btnCriarCopia:         'Create copy',
    visaoQuadro:           'Board',
    visaoLista:            'List',
    visoes:                'Views',
    visaoInclui:           'This view keeps',
    renomear:              'Rename',
    remover:               'Remove',
    informeNomeVisao:      'Give the view a name',
    visaoSalva:            'View saved.',
    visaoRemoverMsg:       'Your orders are not affected.',
    bulkSeraCancelado:     'order will be cancelled.',
    bulkSeraoCancelados:   'orders will be cancelled.',
    bulkDemaisFicam:       'The other {n} are past the stage where cancelling is allowed and stay as they are.',
    outros:                'more',
    semPedidosSub:         'Once an order is created, it shows up here with the progress of each stage.',

    // Orders screen — Inscription redesign
    filtrosRapidos:        'Quick filters',
    visualizacao:          'View',
    resumoEtapas:          'Each number below is a stage of the path.',
    resumoEncerrados:      'Rejected and cancelled orders stay here for reference.',
    resumoNenhum:          'No orders',
    filaDescGestor:        'Open orders that are urgent or have been idle for more than two days land here.',
    filaDescAprovador:     'Orders waiting for your approval land here.',
    filaDescComprador:     'Orders without a buyer and the quotes you took on land here.',
    filaDescFinanceiro:    'Delivered orders waiting for payment land here.',
    filaDescSolicitante:   'Your orders that are still in progress land here.',
    etapas:                'Stages',
    etapaDaFila:           'Stage with the most orders in your queue',
    etapaCurtaSolicitado:  'Request',
    etapaCurtaCotacao:     'Quote',
    etapaCurtaAprovacao:   'Approval',
    etapaCurtaAprovado:    'Approved',
    etapaCurtaComprado:    'Bought',
    etapaCurtaEntregue:    'Delivered',
    etapaCurtaPago:        'Paid',
    etapaCurtaReprovado:   'Rejected',
    etapaCurtaCancelado:   'Cancelled',
    semValor:              'No amount',
    prazoSem:              'No due date',
    prazoVenceHoje:        'Due today',
    prazoFalta1:           '1 day left',
    prazoFaltam:           '{n} days left',
    prazoAtrasado1:        '1 day late',
    prazoAtrasado:         '{n} days late',
    prazoEntregueHoje:     'Delivered today',
    prazoEntregue1:        'Delivered 1 day ago',
    prazoEntregue:         'Delivered {n} days ago',
    prazoPagoEm:           'Paid on {d}',
    prazoReprovadoEm:      'Rejected on {d}',
    prazoCanceladoEm:      'Cancelled on {d}',
    filtrosAtivos1:        '1 active',
    filtrosAtivos:         '{n} active',
    verResultado0:         'No orders',
    verResultado1:         'Show 1 order',
    verResultado:          'Show {n} orders',
    periodoCriacao:        'Created between',
    periodoE:              'and',
    dataInicial:           'Start date',
    dataFinal:             'End date',
    colComprador:          'Buyer',
    colEtapa:              'Stage',
    colPrazo:              'Due',
    ordemPrazo:            'Nearest due date',
    visoesSalvas:          'Saved views',
    salvarVisaoAtual:      'Save this combination',
    visoesVazio:           'Save the current filter combination to come back to it in one tap.',
    carregandoPedidos:     'Loading orders',
    paginacao:             'Pagination',
  },
}

export function t(chave, lang) {
  const idioma = lang || sessionStorage.getItem('praxis_lang') || 'pt'
  return TRADUCOES[idioma]?.[chave] ?? chave
}

export const KANBAN_COLUNAS = [
  STATUS.SOLICITADO,
  STATUS.AG_COTACAO,
  STATUS.EM_APROVACAO,
  STATUS.APROVADO,
  STATUS.COMPRADO,
  STATUS.ENTREGUE,
  STATUS.PAGO,
]

export const STORAGE_PATHS = {
  cotacao:     (pedidoId, cotacaoId) => `pedidos/${pedidoId}/cotacoes/${cotacaoId}`,
  comprovante: (pedidoId, parcelaId) => `pedidos/${pedidoId}/comprovantes/${parcelaId}`,
  anexo:       (pedidoId)            => `pedidos/${pedidoId}/anexos`,
}
